### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by chris10an** [postlight/headless-wp-starter#100]
Is there any documentation?

**Comment by stolinski** [comment]
The Readme covers everything pretty well IMO. Is there something specific you are looking for?

https://github.com/postlight/headless-wp-starter/blob/master/README.md

**Comment by kilinkis** [comment]
@stolinski what are the steps to show custom post types for example? That'd be nice to have documented.

**Comment by tristanoneil** [comment]
@chris10an If there's anything in particular you are looking for help with please feel free to to open another issue and we'll try to help and update any documentation as needed. @kilinkis it looks like https://github.com/postlight/headless-wp-starter/issues/98 already captures this need so I'm closing this out in favor of that issue.
