### ISSUE TITLE
Error establishing database connection to 0.0.0.0

### ISSUE THREAD

**Issue by joshuaiz** [postlight/headless-wp-starter#101]
Hello,
Love this starter kit...
I had everything running and was working with this over the last week. Then I restarted and now can't connect to the database.

I've seen the posts about it installing mysql@8.0.4.11 and how to remove that and install mysql 5.7 which I tried twice but still can't connect.

From there I downloaded the kit again and started a new project fresh and still couldn't connect to the database.

If the default scripts can't work with the mysql that Homebrew installs, can't you specify the mysql 5.7 version there?

In any event, I'm not sure what to do now - this was working and now it isn't. I tried removing mysql completely following the instructions here: https://gist.github.com/vitorbritto/0555879fe4414d18569d
and here: https://coderwall.com/p/os6woq/uninstall-all-those-broken-versions-of-mysql-and-re-install-it-with-brew-on-mac-mavericks, then reinstalling mysql 5.7 with no joy.

What can I try next? Thanks!

**Comment by joshuaiz** [comment]
Update: I've tried editing wp-config.php and using 'localhost' and '127.0.0.1' as the host and still not able to connect.

**Comment by TylerBarnes** [comment]
You might just need to start mysql `brew services start mysql`.
You could also try restarting if it's already started `brew services restart mysql`.
If that doesn't work, hopefully someone else can help!

**Comment by joshuaiz** [comment]
Hi @TylerBarnes that didn't help and it says the mysql server is running.

When I try to connect using `mysql -uroot` I get this error:

`ERROR 2059 (HY000): Authentication plugin 'caching_sha2_password' cannot be loaded: dlopen(/usr/local/Cellar/mysql@5.7/5.7.22/lib/plugin/caching_sha2_password.so, 2): image not found`

So strange...it was working flawlessly for a week and I didn't install any new packages.

**Comment by TylerBarnes** [comment]
Hmm, someone else might chime in with a solution. A quick search seems to come up with a bunch of results though. Maybe check some of these out https://duckduckgo.com/?q=ERROR+2059+(HY000)%3A+Authentication+plugin+%27caching_sha2_password%27+cannot+be+loaded%3A+dlopen(%2Fusr%2Flocal%2FCellar%2Fmysql%405.7%2F5.7.22%2Flib%2Fplugin%2Fcaching_sha2_password.so%2C+2)%3A+image+not+found&t=ffab&atb=v121-2&ia=web

**Comment by joshuaiz** [comment]
Ok I was able to get a new install running but I'll leave this open for now.

It was important to go through the steps to **completely** remove any mysql installs and they are quite sticky - almost like a virus. I went through the steps outlined in these links 4 times:

https://gist.github.com/vitorbritto/0555879fe4414d18569d
https://coderwall.com/p/os6woq/uninstall-all-those-broken-versions-of-mysql-and-re-install-it-with-brew-on-mac-mavericks

**IMPORTANT**: if you are installing for the first time (or want to use `yarn install` again) you should edit line 56 of RoboFile.php from: 

`$this->_exec( 'brew install mysql' );`
to
`$this->_exec( 'brew install mysql@5.7' );`

Otherwise it will install mysql 8.x which causes all of these problems.

Note: this should be updated in the source files. And while I have you here, could you also update WP to 4.9.6 and WP Migrate DB Pro as they are out of date.

Will try to relaunch my previous project and report back in a bit.

**Comment by joshuaiz** [comment]
Ok after a bit of wrangling and updating some post ids after updating, everything is back to normal.

In short to fix this issue on macOS: 

1. make sure you do not have mysql 8.x installed anywhere. Be vigilant about completely removing mysql from your system. **Use `mysqldump` to save your dbs first!**
2. reinstall mysql 5.7 only using 'brew install mysql@5.7`
3. make sure the RoboFile.php is updated with the correct mysql version
4. Fire everything up, load from your dumped sql file and you should be good to go.

Thanks all!
