### ISSUE TITLE
Deployed preview page is a 404 (local is not)

### ISSUE THREAD

**Issue by dbvisel** [postlight/headless-wp-starter#109]
Hi! I'm trying to test out how deployment might work with this – I have WordPress running on remote server, which is working fine, and the front end running on a Now deployment. It works great – except for previewing posts, which gives me a 404. The two servers are separate.

As suggested, I've changed _frontend-origin.php_ to include my frontend URL – no luck. However: when I change it back to _localhost:3000_ and run the front end locally, it works. What am I missing? Now is running on HTTPS (as is my backend) – could that be making a difference?

**Comment by grenben** [comment]
Hi, 
I had this problem to. If I recall i correctly you need to use WP nouce. 
Sorry for the short answer bit I’m away from my Computer. Hopefully this will help you...

**Comment by ginatrapani** [comment]
> It works great – except for previewing posts, which gives me a 404.

What's the URL that throws the 404 exactly?

**Comment by dbvisel** [comment]
Hey! This was not working, but now it is working (when both front end and back end are deployed). I am not sure what I changed in the interim. Sorry, this isn't very helpful!

**Comment by modelm** [comment]
I've found that when the frontend makes an API request for the preview on localhost, it sends the cookies set by WordPress on that domain (http://localhost). The `Cookies` header is included via `{credentials: 'include'}` in the fetch call: https://github.com/postlight/headless-wp-starter/blob/master/frontend/pages/preview.js#L23

Making the same request without the cookie header returns a `rest_cookie_invalid_nonce` 403 API error (which is served by the frontend as a 404). With the frontend on a different domain than WordPress this approach doesn't work at all.

I'm working on a PR that replaces the `fetch` calls with `wpapi` & that library doesn't include a way to send the WP cookies by default, so I'm replacing that functionality with basic auth to make preview work regardless of the frontend domain. A better long-term solution would be to use oauth and have the user authenticate on the frontend domain, but basic auth will serve as a workaround for now.
