### ISSUE TITLE
Wordpress user and login?

### ISSUE THREAD

**Issue by ojack** [postlight/headless-wp-starter#111]
What is the user and login information for wordpress on a fresh install following the README?

Sorry if this info is obvious but I couldn't find it anywhere!

**Comment by morgvanny** [comment]
I think it shows up in the command line in the process somewhere. maybe not a terrible idea to add it to the readme.

username: nedstark
password: winteriscoming

**Comment by ginatrapani** [comment]
Yes, it's in the README!

**Comment by ojack** [comment]
thanks!
