### ISSUE TITLE
rest_missing_callback_param WP-API issue

### ISSUE THREAD

**Issue by omattman** [postlight/headless-wp-starter#116]
Hi,

After adding a CPT to my site i get the following error when accessing wp-json on both `post`, `page` and my CPT. The error says the following for all three of them:

`{`
    `"code": "rest_missing_callback_param","message": "Missing parameter(s): slug",`
        `"data": {`
           `"status": 400,`
`"params": [`
`"slug"`
`  ]`
`}`
`}`

Any clue on how to resolve this? Is this related to the `server.js` or `inc/api-routes.php`

**Comment by modelm** [comment]
This should be solved by https://github.com/postlight/headless-wp-starter/pull/187, feel free to reopen if not.
