### ISSUE TITLE
Docker deployment issues

### ISSUE THREAD

**Issue by jacobmishkin** [postlight/headless-wp-starter#117]
When deploying with docker the react build is still a dev build not a production build. I'm assuming that in the docker file on line 13 'RUN npm run build' is where the production build for react happens, but not sure as I'm new to docker in general. 

Also on redeployment with Now, it rejects the docker build due to docker image size. On first deployment it worked fine, but now the size has tripled. Does anyone know of good ways to reduce the image size?

**Comment by synnovsh** [comment]
In `package.json` change the script `"start"` to `"NODE_ENV=production node server.js"` instead of `"node server.js`". I'd also add a separate script like `"dev":"node server.js"` to run `yarn build && yarn` dev in regular development mode.

**Comment by jacobmishkin** [comment]
Thanks!! works like a charm. Please feel free to close this issue.
