### ISSUE TITLE
Extending file size upload limit

### ISSUE THREAD

**Issue by dasaco** [postlight/headless-wp-starter#118]
Does anybody know how do you extend file size upload limit? Including php.ini with appropriate settings don't work both in /wordpress and /wordpress/wp-content.

Here is **php.in** settings I'm trying to use:

```
upload_max_filesize = 32M
post_max_size = 32M
```

Still gives me an error: 

> file.mp3 exceeds the maximum upload size for this site.

And in the media picker it says that the maximum is 2MB.

**Comment by karatechops** [comment]
@dasaco, did you ever figure this out? It seems like you could create a `php.ini` in your project folder and mount the volume to the container.

**Comment by karatechops** [comment]
I fixed this by adding a `php.ini` to my project base folder and a `COPY` command to my Dockerfile.
`COPY php.ini /etc/php/7.2/cli/php.ini`
