### ISSUE TITLE
 ./install.sh: not found

### ISSUE THREAD

**Issue by piratefresh** [postlight/headless-wp-starter#119]
Hello, I am having some trouble installing with docker, Keep getting stuck on this step when I run "yarn docker:build && yarn docker:start"

Step 12/21 : RUN ./install.sh
 ---> Running in 72afe6e033d3
/bin/sh: 1: ./install.sh: not found
The command '/bin/sh -c ./install.sh' returned a non-zero code: 127
error Command failed with exit code 127.

**Comment by vanmarkic** [comment]
same here... noob talking

**Comment by alexiakl** [comment]
Migrated to docker here: https://github.com/postlight/headless-wp-starter/pull/160
