### ISSUE TITLE
Error: Working on multiple computers without overriding database

### ISSUE THREAD

**Issue by omattman** [postlight/headless-wp-starter#125]
I was working on a different computer and had to move the project to a new computer. The installation process won't let me install all the dependencies while keeping my current Wordpress installation, which causes error on running the provided setup.

When entering `wordpress` folder and running `yarn install` to install the needed packages I don't want to override my existing wordpress database when being prompted:

```
This will replace your current WordPress install. Are you sure you want to do this? (yes/no) [no]:
```

But when answering `no`, the install exits:

```
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

When I try to run `yarn start` and access `localhost:8080/wp-admin/` I get the following error:

```
[Wed Aug 15 19:24:55 2018] PHP Warning:  require_once(index.php): failed to open stream: No such file or directory in /tmp/wp-cli-extract-from-phar-5b7461e470e691.11849663-router.php on line 111
[Wed Aug 15 19:24:55 2018] PHP Fatal error:  require_once(): Failed opening required 'index.php' (include_path='.:/usr/share/php') in /tmp/wp-cli-extract-from-phar-5b7461e470e691.11849663-router.php on line 111
```

How can I fix this so I can continue working on multiple computers with the already existing wordpress database installation?

**Comment by modelm** [comment]
I realize this is an ancient issue but to answer the question, the only WP dependencies of the theme are plugins so you can just run that part of the installer if you like.

https://github.com/postlight/headless-wp-starter/blob/master/docker/install_wordpress.sh#L47

Alternatively (maybe preferably) you can just copy the entire image to the new machine with docker: https://stackoverflow.com/questions/23935141/how-to-copy-docker-images-from-one-host-to-another-without-using-a-repository
