### ISSUE TITLE
Compatibility problem with Wordpress

### ISSUE THREAD

**Issue by anirban0031** [postlight/headless-wp-starter#126]
I think new update of wordpress is not comparable. I tried to use it and every time it takes me to configuration page, I mean installing wordpress. I can't login using given ID and PASS. **Any solution?**

**Comment by modelm** [comment]
Since https://github.com/postlight/headless-wp-starter/releases/tag/v2.0 the latest version of WP is automatically installed when you set up the project. Please give that a try and feel free to reopen this if you still have trouble.
