### ISSUE TITLE
Use WP Local Docker

### ISSUE THREAD

**Issue by cr101** [postlight/headless-wp-starter#130]
I need to use Elasticsearch, Memcached, phpMyAdmin, phpMemcachedAdmin. Is it possible to use [WP-Local-Docker](https://github.com/10up/wp-local-docker) with this starter kit?

**Comment by freddiemixell** [comment]
You should just get this WordPress environment running and then use the All In One Migration plugin for WordPress make a copy. Then in your docker install of WordPress download All in one migration and import. Now you have the same setup, just make sure you change the frontend-origin.php file to whatever your production site will be.

**Comment by cr101** [comment]
I've just come across Zeit's [Serverless Docker](https://zeit.co/blog/serverless-docker) which sounds like a better alternative

**Comment by modelm** [comment]
You can use any WordPress backend (docker, hosted, whatever) with the included React frontend, just change the API URL in https://github.com/postlight/headless-wp-starter/blob/master/frontend/config.js accordingly.
