### ISSUE TITLE
Next.js version should be semver-compliant instead of "latest"

### ISSUE THREAD

**Issue by VilhelmNielsen** [postlight/headless-wp-starter#132]
**What:**
The frontend package.json should specify a version of Next.js instead of "latest"

**Why:**
Using "latest" is bad practice in case of any changes or deprecation to Next.js in future versions.

Specifying Next.js v6 or would also justify using _app.js (https://nextjs.org/docs/#custom-%3Capp%3E) as a replacement for the PageWrapper-HOC and Layout component, making the code cleaner and allowing all the bonuses of _app.js including Page Transitions.

**Comment by modelm** [comment]
fixed in https://github.com/postlight/headless-wp-starter/blob/feat-dockerer/frontend/package.json
