### ISSUE TITLE
Docker is running the development server

### ISSUE THREAD

**Issue by chandra-sekar** [postlight/headless-wp-starter#133]
Docker runs the PHP development server when deployed on a VPS (screenshot below). I guess the development server is single threaded and slow (Wait time is long for server ping). Is this intended or am I missing anything? Can someone with experience running this on production shed some light on this (I am running this on a Digital ocean droplet)? Thanks!

<img width="589" alt="image" src="https://user-images.githubusercontent.com/7146130/44721066-5af4e900-aae6-11e8-89c8-3fd4b991d4a4.png">

**Comment by modelm** [comment]
That's intended before the switch to the official Docker Wordpress image in https://github.com/postlight/headless-wp-starter/tree/feat-dockerer - after that, the web server is the default Apache.
