### ISSUE TITLE
docker frontend container stop immediately 

### ISSUE THREAD

**Issue by ProjectKarol** [postlight/headless-wp-starter#141]
When I try run docker  frontend container stops immediately  after start 
I try run locally  on mac os

**Comment by freddiemixell** [comment]
I haven't personally tried using the docker WordPress version of this repo but in my experience its much easier to pull out the Postlight theme and use Local by Flywheel to serve your WordPress install. This is actually just using docker in the background but in a very user friendly way.

**Comment by modelm** [comment]
@ProjectKarol Do you still see that behavior using the lastest release https://github.com/postlight/headless-wp-starter/releases/tag/v2.0 ?
