### ISSUE TITLE
permissions denied with sql as well aswp config 

### ISSUE THREAD

**Issue by britt6612** [postlight/headless-wp-starter#144]
[
<img width="1056" alt="screen shot 2018-10-23 at 1 56 01 pm" src="https://user-images.githubusercontent.com/42451602/47387059-86054e80-d6cb-11e8-9293-785229b7f8d9.png">
<img width="1060" alt="screen shot 2018-10-23 at 1 56 14 pm" src="https://user-images.githubusercontent.com/42451602/47387066-8998d580-d6cb-11e8-8e20-adeacb755b67.png">

](url)

**Comment by freddiemixell** [comment]
@britt6612 check out the Readme you'll see that this issue has been addressed! Hopefully that will solve your issue.
