### ISSUE TITLE
"invalid JSON response body" on yarn start in frontend

### ISSUE THREAD

**Issue by stlasalle** [postlight/headless-wp-starter#148]
Hello.

I am having the same problem as described in https://github.com/postlight/headless-wp-starter/issues/71, and am opening my own issue as I have tried the steps described there.

When running `yarn install && yarn start` in /frontend I get:
`invalid json response body at http://localhost:8080/wp-json/menus/v1/menus/header-menu/ reason: Unexpected token < in JSON at position 0` when trying to reach `localhost:3000` in both Firefox and Chromium.

I am running on arch linux. I have cloned the directory, installed and setup mariadb, installed php with mysqli, and the backend is running fine. I have installed and connected to wordpress and can reach the default page at localhost:8080.

I tried curling the URL specified and received [this HTML](https://github.com/postlight/headless-wp-starter/files/2580674/output.txt), which is the same thing seen on localhost:8080.

I am hoping that this is a silly misconfiguration issue on my behalf. 

For clarity, I am using Node 11. I am not sure that this will be making the difference but just in case.

Thanks

**Comment by modelm** [comment]
See https://github.com/postlight/headless-wp-starter/issues/169#issuecomment-461550683 - you'll need to examine the output of http://localhost:8080/wp-json/menus/v1/menus/header-menu/ to learn why the JSON is invalid. If it's literally the same as the homepage then WordPress didn't install correctly, you may be missing the theme or the menu endpoint plugin or both.
