### ISSUE TITLE
How to get categories name in index ?

### ISSUE THREAD

**Issue by apradipta10** [postlight/headless-wp-starter#154]
helo, i was modified my frontend. showing up the title of post, excerpt, author, and post date. But i dont know how to show up category name. do you know ?

show the title = {post.title}
excerpt = {post.excerpt.renderred}
post date = {post.date}
category name ? {post.categories} the result is "1".

**Comment by modelm** [comment]
The WP REST API includes only a category ID in the posts endpoint. So you have to add that data yourself with a filter something like this (this includes all taxonomies, not just category):


```php
/**
 * Add taxonomy data to post API responses.
 *
 * @param WP_REST_Response $response The response object.
 * @param WP_Post          $post     Post object.
 * @param WP_REST_Request  $request  Request object.
 */
add_filter( 'rest_prepare_post', function( $response, $post, $request ) {
	foreach ( get_post_taxonomies( $post ) as $taxonomy_name ) {
		$response->data[ "${taxonomy_name}_data" ] = [];
		$terms = get_terms(
			[
				'taxonomy'   => $taxonomy_name,
				'object_ids' => [ $post->ID ],
			]
		);
		foreach ( $terms as $term ) {
			$response->data[ "${taxonomy_name}_data" ][ $term->term_id ] = [
				'name' => $term->name,
				'slug' => $term->slug,
			];
		}
	}
	return $response;
}, 10, 3 );
```

**Comment by modelm** [comment]
Alternatively, look up the category itself with a second API call using the ID from the posts data:

https://developer.wordpress.org/rest-api/reference/categories/
