### ISSUE TITLE
Two projects?

### ISSUE THREAD

**Issue by braco** [postlight/headless-wp-starter#161]
There's quite a few people looking into pairing Gatsby with Wordpress.

Would you guys ever consider forking this into two projects? One for Wordpress optimized to be a headless CMS, the other for the front end. This way you could pair the first project with different rendering platforms like Next or Gatsby.

**Comment by joshuaiz** [comment]
Not to toot my own horn here but I ported our WordPress starter theme to a WordPress + Gatsby starter that's ready-to-go here: https://github.com/joshuaiz/plate-for-gatsby

All that said, I have used and continue to use the Postlight starter for other projects as it is very adaptable and really well done.
