### ISSUE TITLE
Allow support for custom post types in json preview

### ISSUE THREAD

**Issue by stevengrimaldo** [postlight/headless-wp-starter#163]
https://github.com/postlight/headless-wp-starter/blob/99b4d7bbc4b327659da48a520e6d054c2cdf6c21/wordpress/wp-content/themes/postlight-headless-wp/index.php#L4

if you changed line 4 to read like so it would allow for custom post types to have a json preview like posts and pages do:

`header('Location: /wp-json/wp/v2/' . get_post()->post_type . '/' . get_post()->ID);`

**Comment by modelm** [comment]
fixed by https://github.com/postlight/headless-wp-starter/commit/b5de0193d98127f5b69a88fad491e4423a46d064
