### ISSUE TITLE
Building without Docker?

### ISSUE THREAD

**Issue by Triphys** [postlight/headless-wp-starter#165]
Hey,

Just trying to figure out if it's possible to build the app without docker? Have tried running "npm run build" and "yarn build" which both seems to run fine but doesn't build any files at all so I'm at a loss :/

**Comment by alexiakl** [comment]
The app has been updated to run only using Docker to avoid a lot of setup issues on different environments.
I **recommend** using Docker for setup but if you choose to run it without it, you need to do manual changes or check the last commit before migrating to docker: `99b4d7bbc4b327659da48a520e6d054c2cdf6c21`

**Comment by alexiakl** [comment]
Use Docker only for development, build it on your localhost, and deploy only wordpress and the frontend.

**Comment by Triphys** [comment]
@alexiakl alright, but how do I build it? Because now it generates nothing, if I run "yarn build" I get a return with:
```
yarn run v1.12.3
$ next build
[3:59:08 PM] Compiling server
[3:59:08 PM] Compiling client
[3:59:11 PM] Compiled server in 3s
[3:59:11 PM] Compiled client in 3s
✨  Done in 4.35s.
```

But nothing is build and no new files anywhere :(
