### ISSUE TITLE
/bin/sh: 1: ./install.sh: not found on docker for windows using linux containers

### ISSUE THREAD

**Issue by anderskitson** [postlight/headless-wp-starter#171]
I have tried to run `docker-compose up -d` in windows and I get the following error.

```
/bin/sh: 1: ./install.sh: not found
ERROR: Service 'wp-headless' failed to build: The command '/bin/sh -c ./install.sh' returned a non-zero code: 127
```

I thought docker is supposed to take care of running the linux container so this should work, I thought. I went and tried to do this is windows linux subsystem in ubuntu, and when I run the same command I get the following error there. 

```
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
```

Thanks ahead of time

**Comment by avocadoras** [comment]
Same. Running macos 10.14. However, it works if I just run `yarn install` in the root project folder.

**Comment by anderskitson** [comment]
@avocadoras I got something working now. Instead of running docker in the linux subsystem in bash. I just installed docker for windows and ran `docker-compose up -d` and everything worked. It actually looks like when you run `docker exec -it wp-headless /bin/bash` it spins up bash and then you can run `yarn` inside of that. I think that is how that works. But your running mac so I think your issues is quite different.

**Comment by avocadoras** [comment]
@anderskitson I was typing `docker-compose up -d docker-compose.yml` instead of `docker-compose up -d`.

**Comment by barro32** [comment]
I'm getting `/bin/sh: 1: ./install.sh: not found` on Ubuntu 18.04

**Comment by dave52** [comment]
I'm getting the same issue as @anderskitson. 

I installed Docker for windows, and I'm running `docker-compose up -d` command on windows 10 from powershell terminal...

```
Step 11/21 : RUN ./install.sh
 ---> Running in f53975d9a467
/bin/sh: 1: ./install.sh: not found
ERROR: Service 'wp-headless' failed to build: The command '/bin/sh -c ./install.sh' returned a non-zero code: 127
```

I also installed WSL the Ubuntu distro, and received the same error as anderskitson too...

```
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
```

Any help would be appreciated, thank you

**Comment by avocadoras** [comment]
I think this is a common issue. try `cd wordpress` and then run `npm i` or `yarn install`

**Comment by dave52** [comment]
Since i'm on Windows I can't terminate `$ chmod +x install.sh && chmod +x mysql_config.sh && ./install.sh` as it's a bash command. Need to get Docker running to handle this for me. 

Regardless, I appreciate the response.

**Comment by dave52** [comment]
Got it fired up! Not totally certain what resolved this.

I changed the Docker container to run Windows containers from Linux containers, which prompted Docker to ask for permission to switch containers, so maybe that was not granted before. Also uninstalled and re-installed Docker before that.

**Comment by anderskitson** [comment]
Well now I am getting the same error, and I haven't changed anything other then doing a fresh install on a new repo that I cloned from github. I tried restarting docker, I could do a factory reset but don't want to lose some other containers. I will report back if I can get it working.

**Comment by anderskitson** [comment]
Hmm, it's a really strange bug after another docker factory reset it works again, seems like a docker for windows bug.

**Comment by anderskitson** [comment]
Also somewhat unrelated, but if anyone can't get hot/live reload to work I had to run the yarn install and yarn start for the front end in Windows Subsystem for Linux and now I finally have a development environment up and running.

**Comment by halahasz** [comment]
Removing the CR character from CR/LF line endings for install.sh and docker/install_php_extensions.sh helped me to resolved this issue.
In command line  go to folder: headless-wp-starter and type: cat install.sh | sed '/\015/d' >newinstall.sh then delete install.sh and rename 
newinstall.sh => install.sh. The same for install_php_extensions.sh. Should work, here is some explanation of this problem: 
https://stackoverflow.com/questions/4182122/syntax-error-near-unexpected-token-elif. Good luck! :)

**Comment by dave52** [comment]
Anyone having luck with building a project with this boilerplate on Windows running Docker?

Hot reloading doesn't seem to work. When I initially run `$ cd frontend && yarn install && yarn start` so long as I don't have errors, content changes render but no reloading after. If I update a page with mark up and refresh browser, that doesn't work either.

**Comment by cedrox** [comment]
Hello, 
I confirm that this is a CR LF trouble. 
If you are on widows, you can change CR LF to LF with notepad ++ like this 
http://sql313.com/index.php/43-main-blogs/maincat-dba/62-using-notepad-to-change-end-of-line-characters

Thanks

**Comment by ttstauss** [comment]
This really threw me off for longer than it should have. @cedrox, thanks for the tip.

For anyone using **Visual Studio Code** on **Windows 10**, here is an easy way to fix this:

Open **install.sh** (in the root directory). Look for "CRLF" in the bottom right of the VSCode window. Click it and you'll see an option drop down from the top of the window. Select "LF" and save the document.

Follow the same instructions for **install_php_extensions.sh** in the **docker** folder.

From there you should be able to run `docker-compose up -d` successfully.

**Comment by geocine** [comment]
On mac I ran this 
```
find . -type f -print0 | xargs -0 dos2unix
```

**Comment by PhoeniXAbhisheK** [comment]
A big thanks to @halahasz , @cedrox , and @ttstauss for the help. 🙌

**Comment by GentooHTF** [comment]
Thanks for the CRLF fix! ! !  This is an obscure error.

**Comment by ElmarDeGroot** [comment]
wish I found this thread a lot sooner :(

**Comment by bkakilli** [comment]
Mine is a different and silly mistake. For those who are not careful like me in the future:
For multiple line RUN commands, do not use double back-slash (**\\\\**) between lines, just one (**\\**) will do :)

**Comment by micpog** [comment]
Thankfully only one day of searching for this solution :) Thanks!

**Comment by sonali-yadav** [comment]
Thank you @halahasz and @cedrox .
You saved my exam!

**Comment by modelm** [comment]
I believe this is fixed after the update to the install script in https://github.com/postlight/headless-wp-starter/pull/244. I tried running `dos2unix` on it and git reported no change.

**Comment by prit2596** [comment]
> This really threw me off for longer than it should have. @cedrox and @halahasz, thanks for the tip.
> 
> For anyone using **Visual Studio Code** on **Windows 10**, here is an easy way to fix this:
> 
> Open **install.sh** (in the root directory). Look for "CRLF" in the bottom right of the VSCode window. Click it and you'll see an option drop down from the top of the window. Select "LF" and save the document.
> 
> Follow the same instructions for **install_php_extensions.sh** in the **docker** folder.
> 
> From there you should be able to run `docker-compose up -d` successfully.

A big thanks to @ttstauss. It really pissed me off because the docker container I was running on mac machine was not throwing the error and on windows I was getting this error which was very weird.

**Comment by sanzenwin** [comment]
> Removing the CR character from CR/LF line endings for install.sh and docker/install_php_extensions.sh helped me to resolved this issue.
> In command line go to folder: headless-wp-starter and type:
> 
> cat install.sh | sed '/\015/d' >newinstall.sh
> 
> then delete install.sh and rename newinstall.sh => install.sh. The same for install_php_extensions.sh. Should work, here is some explanation of this problem:
> https://stackoverflow.com/questions/4182122/syntax-error-near-unexpected-token-elif.
> Good luck! :)

Nice!

**Comment by saaagar** [comment]
> This really threw me off for longer than it should have. @cedrox and @halahasz, thanks for the tip.
> 
> For anyone using **Visual Studio Code** on **Windows 10**, here is an easy way to fix this:
> 
> Open **install.sh** (in the root directory). Look for "CRLF" in the bottom right of the VSCode window. Click it and you'll see an option drop down from the top of the window. Select "LF" and save the document.
> 
> Follow the same instructions for **install_php_extensions.sh** in the **docker** folder.
> 
> From there you should be able to run `docker-compose up -d` successfully.

Amazing, Thank you so much. I had same problem while using [moeen-basra/laravel-react](https://github.com/moeen-basra/laravel-react) repo. Changing CRLF did the job.
