### ISSUE TITLE
docker-compose up -d fails to build wp-headless

### ISSUE THREAD

**Issue by avocadoras** [postlight/headless-wp-starter#173]
getting this error after running `docker-compose up -d` --->
ERROR: Service 'wp-headless' failed to build: The command '/bin/sh -c apt-get update && apt-get install -yq curl php gnupg wget sudo lsb-release debconf-utils less' returned a non-zero code: 100

**Comment by NearFutureBand** [comment]
The same problem. Just cloned the repo and run this command. Also tried to install curl, php, gnupg and others manually and that was successfully. Ubuntu 16.04 LTS

**Comment by alyoshz** [comment]
Same here

**Comment by scottdevito** [comment]
I got this error but then stopped the container, deleted it, deleted all images, restarted Docker and retried docker-compose up -d and it worked. 

Just a note: I don't have any other containers/images in Docker so I was able to wipe everything without worry.

**Comment by stud-mai** [comment]
For me quite similar problem - cloned the repo, run command `docker-compose up -d`, got an error:
```
ERROR: for wp-headless  Cannot start service wp-headless: driver failed programming external connectivity on endpoint wp-headless (81a6841262a2084ec98ad660b567e43dfac5deca7376b1967569cba9c5e4fa82): Error starting userland proxy: Bind for 0.0.0.0:8080: unexpected error Permission denied
```

**Comment by stud-mai** [comment]
> For me quite similar problem - cloned the repo, run command `docker-compose up -d`, got an error:
> 
> ```
> ERROR: for wp-headless  Cannot start service wp-headless: driver failed programming external connectivity on endpoint wp-headless (81a6841262a2084ec98ad660b567e43dfac5deca7376b1967569cba9c5e4fa82): Error starting userland proxy: Bind for 0.0.0.0:8080: unexpected error Permission denied
> ```

The issue was occurred because the port :8080 was busy by Tomcat server. The releasing the port resolved my problem

**Comment by modelm** [comment]
fixed by using the Docker WordPress image in https://github.com/postlight/headless-wp-starter/blob/feat-dockerer/docker-compose.yml
