### ISSUE TITLE
How I can update Wordpress version?

### ISSUE THREAD

**Issue by ppsirius** [postlight/headless-wp-starter#174]
The new Gutenberg edit panel is added to the latest version, how I can update wordpress version in docker?

**Comment by edelinpetrov** [comment]
Replace the WP download command within the RoboFIle.php with the following(or w/e version you would like)
`$this->wp( 'core download --version=5.0.2 --locale=en_US --force' );`

**Comment by modelm** [comment]
fixed in https://github.com/postlight/headless-wp-starter/blob/feat-dockerer/docker/install_wordpress.sh
