### ISSUE TITLE
Now v2 deployment example?

### ISSUE THREAD

**Issue by wickedst** [postlight/headless-wp-starter#175]
Hi there. I've been having a lot of fun with headless-wp-starter and I am nearly ready to go live with my first project based on it. 

Just considering deployment options and I am really curious about Now. Does anyone have experience with deploying to the platform who could provide a sample `now.json` that would work with the latest commit of headless-wp-starter?

Thanks again

**Comment by wickedst** [comment]
After more research it seems docker is not supported in the latest version of Now
https://spectrum.chat/zeit/general/sad-to-see-docker-not-supported-in-now-v2~d04c5b35-60b8-4f1c-b327-0a3f93999503

However someone might have a configuration for the front-end Next app?

**Comment by dbvisel** [comment]
I ran into this as well! It seems like the argument on the Now/Next Spectrum seemed to be that you shouldn't be using server.js with the new Now. I don't want to rework everything, so I'm staying with v1 despite the annoying warnings.

**Comment by wickedst** [comment]
I am going to go with a VPS (DigitalOcean) back end and then the front-end Next app on Now or the AWS PaaS option.

For the WordPress setup I wanted something preconfigured so I do not have to worry too much about security, caching or anything server related. I was considering the Roots suite but I saw DigitalOcean has a new OpenLiteSpeed WordPress one click install so I opted for that – it seems to have insanely good performance compared to a vanilla LAMP stack.

The final piece of the puzzle will be deployments and refactoring my repo, setting up local and production environment variables and so on. As far as WP I think I will just deploy the WordPress theme and manage the WordPress install manually for now.

On a side note – if any of the project authors are browsing here, is there any plans for a Slack or something similar where we could discuss topics like this?

**Comment by wickedst** [comment]
If anyone is curious the Now v2 deployment is pretty easy, I just followed the steps here: https://zeit.co/examples/nextjs-static/

**Comment by dbvisel** [comment]
> If anyone is curious the Now v2 deployment is pretty easy, I just followed the steps here: https://zeit.co/examples/nextjs-static/

It seems like they've improved the documentation since they rolled out v2 – at first this didn't work at all. 

But I already have an installation that's pretty dependent upon _server.js_ for routing. I can't say that I'm excited about the prospect of reworking that entirely to make it work on a service that may change at any minute. I really don't want to go to AWS, but maybe that's where I'm headed.

**Comment by wickedst** [comment]
So I have an update on this – the now v2 deployment is not so easy as the serverless architecture means we can not / do not use the express `server.js` in production (we still need it for development purposes though).

Instead we add routes to the `now.json` file. I've put everything in a gist in case anyone who is interested in deploying this project to now finds this thread. It should be quite easy to see which lines you have to add / change in your project, and then simply do `now` in /frontend. Of course this is only for deployment of the frontend and not WP.

https://gist.github.com/wickedst/a65bf76c52e812539abc2ee7c16408aa

**Comment by cordial** [comment]
Have you actually managed to get this to work? I have copied your example but I am getting an issue that seems to be an issue with wpapi and now v2. Which has been documented/discussed here -
 
https://spectrum.chat/zeit/now/trying-to-make-wordpress-work~c623bcf6-3853-4f79-a598-2b410501538b

did you not have this issue or perhaps did and got round it somehow?
