### ISSUE TITLE
Wordpress asks to reinstall after restarting docker

### ISSUE THREAD

**Issue by anderskitson** [postlight/headless-wp-starter#176]
Everything has been working fine for me up until this point. I restarted my computer after the reboot the `localhost:8080` was no long accessible I expected this. So I ran a `docker-compose up -d` that didn't work so I restarted docker (not factory reset, restarted) and then ran `docker-compose down` and then ran again `docker-compose up -d` `localhost:8080` was back however wordpress was asking me to do a fresh install, do I have to run yarn install every time docker is restarted or I run `docker-compose down` that doesn't seem to make sense to me. I had already installed some plugins so I was hoping to not have to reinstall them. Hope someone can help, Thanks.

**Comment by geocine** [comment]
@anderskitson 
To stop a docker container you should've done `docker-compose stop` . `docker-compose down` , everything you have on the container will be removed.

**Comment by florinme** [comment]
Mother F%$*&@#. LOL.

Just wanted to vent because I did this also. What is the process to bring it back up when you've already composed up? I've been using `docker-compose up -d wp-headless` everytime to start the dev server. Just simply assumed that it's fellow `down` might do the opposite. Seems like `up` is used to both run the original config, and to bring it back up. Should I be using `start.` If so, that's not what it says in the readme.

**Comment by modelm** [comment]
This is discussed in the docker compose FAQs: https://docs.docker.com/compose/faq/#whats-the-difference-between-up-run-and-start

Is there a particular part of the README here you think could be improved? It never says to run `down` but if you can suggest an improvement that would clarify things, that might help.

**Comment by florinme** [comment]
@modelm. Thanks for that doc. This is obviously docker's doing. If you think about it, the pairs are `up/stop`, vs `up/down` or `start/stop`.... If I had more experience with Docker I would have caught, and I was lucky enough to have a deployed staged version of WordPress I was pushing up to; so It was easy to get it back up and running. But I basically destroyed both wp-headless and wp-database; which is super destructive. I would imagine someone else might do this. I'd just add a note in your documentation that shows how you'd stop the dock instances. For example:

Stop top, either don't run (`-d`) when doing `start` and break out using the terminal when you're done, or run `docker-compose stop.` And also mention what you did above, that running `docker-compose down` will remove everything from the container.
