### ISSUE TITLE
view of post/page from post/page list

### ISSUE THREAD

**Issue by geocine** [postlight/headless-wp-starter#186]
Previewing pages has already been fixed on #14 . However viewing pages should also be fixed so that the url will use the `get_frontend_origin`

<p align="center"><img src="https://i.imgur.com/yqzuiEA.png"></p>

**Comment by mcorrello** [comment]
This has been fixed and merged in [PR #329](https://github.com/postlight/headless-wp-starter/pull/329)

**Comment by geocine** [comment]
Thanks . I can't even remember I opened this issue 😂.
