### ISSUE TITLE
Name is not a unique identifier

### ISSUE THREAD

**Issue by jasonbahl** [postlight/headless-wp-starter#197]
https://github.com/postlight/headless-wp-starter/blob/ad89721c582b46f98d404540a780808b25246cd5/frontend-graphql/src/components/Page.js#L11

Hello,

The slug on hierarchical post types is not a unique identifier which is why it’s not a filter provided the `pageBy` query. 

For example you could have `/contact/about`, `/staff/about`, and `/company/about` Each with the slug of `about`

There is a `pageBy( uri: “..." )` query you can use

So `pageBy( uri: “staff/about” )` will get you the correct page here.

**Comment by alexiakl** [comment]
Thank you @jasonbahl will look into it
