### ISSUE TITLE
Wordpress API routes file removed.

### ISSUE THREAD

**Issue by wrongakram** [postlight/headless-wp-starter#199]
In the previous version, I used the routes file to remove the /page/ directory in the URL. Having trouble doing the same now. Any tips?

`example.com/page/about` 

change to 

`example.com/about`

**Comment by akramk22** [comment]
Seems like the frontend folder is dependent on the frontend-graphql's routes. Is this true? Removing graphql frontend seems to break the frontend project.

**Comment by alexiakl** [comment]
Maybe this issue can help:
[#155 URL structure (without "/page/" and "/post/" )](https://github.com/postlight/headless-wp-starter/issues/155)

Closing.
