### ISSUE TITLE
CORS issue after installation on the frontend app

### ISSUE THREAD

**Issue by ghoshnirmalya** [postlight/headless-wp-starter#20]
After installation, I'm getting this issue on the console of the frontend app:

```
Failed to load http://localhost:8080/wp-json/menus/v1/menus/main: Redirect from 'http://localhost:8080/wp-json/menus/v1/menus/main' to 'http://localhost:8080/wp-json/menus/v1/menus/main/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

<img width="1677" alt="screen shot 2017-11-10 at 11 16 46 pm" src="https://user-images.githubusercontent.com/6391763/32671398-485893cc-c66d-11e7-9970-5227afff1db8.png">

Also, if I use some Chrome plugin to allow CORS, I get the following error:

<img width="1678" alt="screen shot 2017-11-10 at 11 18 15 pm" src="https://user-images.githubusercontent.com/6391763/32671478-9399adee-c66d-11e7-9628-85ea8c8b27f5.png">

**Comment by ginatrapani** [comment]
@ghoshnirmalya if you modify this line https://github.com/postlight/headless-wp-starter/blob/master/frontend/components/Header.js#L17 to add a / after main, and avoid that redirect, does it make a difference?

Also, just to confirm: is this Mac or Linux?

**Comment by ghoshnirmalya** [comment]
@ginatrapani No change happens even if I add `/` after main.

I'm using Mac.

**Comment by ginatrapani** [comment]
I can't seem to reproduce this. Anyone else seeing it?

**Comment by johhansantana** [comment]
weird, did you just cloned/download did `yarn install && yarn start` on wp server folder then went to `./frontend` and did `yarn install && yarn dev` and it gave you this?

**Comment by ghoshnirmalya** [comment]
@johhansantana Yes.

**Comment by ghoshnirmalya** [comment]
Now, again I cloned the repo and followed the following steps:

1. `yarn install && yarn start`
2. `cd  frontend && yarn install && yarn start`
3. I log into the `wp-admin` and change the theme to `Postlight Headless WordPress`.

Now, when I go to `http://localhost:3000/`, I get the following:

```
maximum redirect reached at: http://localhost:8080/wp-json/
FetchError: maximum redirect reached at: http://localhost:8080/wp-json/
    at ClientRequest.<anonymous> (/Users/nirmalya/Development/personal/github/headless-wp-starter/frontend/node_modules/node-fetch/index.js:147:13)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```
and, when I go to `http://localhost:8080/wp-json/`, I get the following:

```
This page isn’t working

localhost redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
```

**Comment by ginatrapani** [comment]
> I log into the wp-admin and change the theme to Postlight Headless WordPress.

You shouldn't have to do this part, that should've happened during `yarn install`. Could you share the out put of that command?

**Comment by ghoshnirmalya** [comment]
This is the output:

```
yarn install v1.3.2
$ chmod +x install.sh && ./install.sh
Warning: homebrew/php/wp-cli 1.4.1 is already installed
Warning: homebrew/php/robo 1.1.1 is already installed
Warning: mysql 5.7.20 is already installed, it's just not linked.
You can use `brew link mysql` to link this version.
Starting MySQL
 SUCCESS!
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 143
Server version: 5.5.5-10.2.11-MariaDB Homebrew

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 171203 11:08:19 mysqld_safe A mysqld process already exists
exit
Bye
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
$ robo wordpress:setup

 This will replace your current WordPress install. Are you sure you want to do this? (yes/no) [no]:
 >

✨  Done in 14.07s.
```

**Comment by ginatrapani** [comment]
Ah, the issue is this message:

> Warning: mysql 5.7.20 is already installed, it's just not linked.
> You can use `brew link mysql` to link this version.

See this comment:

https://github.com/postlight/headless-wp-starter/issues/35#issuecomment-349430280
