### ISSUE TITLE
Multisite Setup

### ISSUE THREAD

**Issue by tinhochu** [postlight/headless-wp-starter#204]
Hey guys!
This it's an amazing setup!
Currently, I will love to move forward with this setup, but the thing that stops me is, Multisite.
I Handling a Multisite for a lot of clients
Any way that we could approach it with this setup?

Regards

**Comment by modelm** [comment]
Hello, this kit should work fine with multisite. You will probably need multiple frontends and/or some way to determine the site context when the frontend(s) talk to the backend.

**Comment by dwojtyca** [comment]
Hello, sorry for re-opening this issue, but I'm trying to connect my frontend to multisite wp backend and no luck yet. Basically, from browser perspective everything works fine (I'm able to open both my WP REST APIs using browser). 

Unfortunately, when frontend (NextJS) is trying to reach WP REST API on server side using node wpapi, it crashes (ECONNREFUSED). 

Could you please give me any advices on that? @tinhochu did you solve this somehow?
