### ISSUE TITLE
Wp-headless & Frontend 

### ISSUE THREAD

**Issue by Brahmrshi1** [postlight/headless-wp-starter#205]
He guys I am window user and use docker toolbox for the docker work in the window.
After following all step I found this output. 

![headless_docker](https://user-images.githubusercontent.com/44024125/54817870-f1c10700-4cbd-11e9-8126-3628d08e4921.png)

And Also get an error in Frontend side also.

![headless_docker](https://user-images.githubusercontent.com/44024125/54818038-5b411580-4cbe-11e9-9068-e13fd61201a5.png)

So please tell me how to solve it

**Comment by queceo** [comment]
I fixed the frontend by adding the following yarn packages: 
https://yarnpkg.com/en/package/chokidar
https://yarnpkg.com/en/package/chokidar-cli
*probably only adding the cli will be enough.

And changed line 8 to: 
`"start": "node server.js CHOKIDAR_USEPOLLING=true"`
