### ISSUE TITLE
apt-get update error

### ISSUE THREAD

**Issue by andrewtrecha** [postlight/headless-wp-starter#213]
I'm receiving the following error when trying to spin up locally (Mac OS Mojave):

ERROR: Service 'wp-headless' failed to build: The command '/bin/sh -c apt-get update; 	apt-get install -yq mysql-client netcat sudo less git unzip' returned a non-zero code: 100

I've reinstalled docker.

docker version 18.09.2, build 6247962
docker-compose version 1.24.0, build 0aa59064
docker-machine version 0.16.1, build cce350d7

Is this a configuration error on my machine, or something wrong with the docker file?

I had postlight running locally recently, and when trying to create a new installation, I keep getting the above error.

**Comment by hankroark** [comment]
Fresh pull, I got the same error.  Anyone get it resolved?

**Comment by hankroark** [comment]
I resolve the issue for myself: https://github.com/postlight/headless-wp-starter/pull/221

**Comment by magidmroueh** [comment]
this issue is solved by this [PR](https://github.com/postlight/headless-wp-starter/pull/221).
