### ISSUE TITLE
Is it good for Woocommerce ?

### ISSUE THREAD

**Issue by seba-t** [postlight/headless-wp-starter#214]
Hey is it good for backend like WooCommerce? I would like to build my own theme with NextJS or Gatsby

**Comment by patrykgaluszka** [comment]
Hey,
It's just a boilerplate theme for making wordpress with separate front-end layer and API communication between WP and react-based front-end. As far as I've investigated you need to register WooCommerce endpoints by your own (it's not a big deal) and somehow handle the payment. While WooCommerce gives you solutions or has dedicated plugins, your cannot handle payment via wordpress API. Then you need to use your payment service (ie. PayPal, platnosci24 ;)) API to make a payment and let Wordpress know that status of order has changed to paid. I'm not sure about Gatsby, it's a different approach than NextJS.
