### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by berkaypehlevan** [postlight/headless-wp-starter#218]
I am using ubuntu 18.04 in my vps.
Do everything but i got error.

Unhandled Rejection (TypeError): Cannot read property 'status' of undefined
Function._callee$
./pages/index.js:46
  43 | 
  44 |   return { page, posts, pages };
  45 | } catch (err) {
> 46 |   if (err.data.status === 403) {
  47 |     tokenExpired();
  48 |   }
  49 | }

**Comment by nvdlug** [comment]
Probably because the wordpress backend isnt running so he cant retrieve any data.

**Comment by FDiskas** [comment]
Change: pages/index.js :izakaya_lantern:
![image](https://user-images.githubusercontent.com/468006/61863176-c5b9ca80-aed7-11e9-90f0-88b49cc9884a.png)

**Comment by FDiskas** [comment]
The main reason probably that wp-headless container is not running :o

**Comment by magidmroueh** [comment]
Make sure docker installation is done and all containers are running.
