### ISSUE TITLE
Fetching wordpress__wp_media

### ISSUE THREAD

**Issue by ttstauss** [postlight/headless-wp-starter#219]
When fetching certain endpoints, I've noticed that some of the entities get skipped. Is there a reason this happens?

Here is an example of when it fetches the wordpress__wp_media (wp-json/wp/v2/media) endpoint:

```
=== [ Fetching wordpress__wp_media ] === http://localhost:8080/wp-json/wp/v2/media
⢀ source and transform nodes
Total entities : 622
Pages to be requested : 7
⠁ source and transform nodes -> wordpress__wp_media fetched : 607
Fetching the wordpress__wp_media took: 6190.797ms
```

You'll notice that it found 622 entities, but only fetched 607. This is causing images to be missed.

Any ideas why this would be happening?

**Comment by magidmroueh** [comment]
@ttstauss this issue is not replicated, can you provide more details ? and the full request/response plz.

**Comment by magidmroueh** [comment]
closing this issue for now.
