### ISSUE TITLE
Install on Debian Stretch fails

### ISSUE THREAD

**Issue by mdrovdahl** [postlight/headless-wp-starter#22]
Database setup steps fail with:

`ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)`

This leaves an incomplete WordPress install. Workaround is to edit RoboFile.php such that is has mysql root credentials which work.

Looks like presetting the root password via `debconf-set-selections` in https://github.com/postlight/headless-wp-starter/blob/master/install.sh#L4 maybe fails, but I haven't yet determined why.

**Comment by george-haddad** [comment]
Hi there. 

When beginning the install process; is MySQL already installed and if so is there a root password already set?

**Comment by mdrovdahl** [comment]
Howdy @george-haddad 

This was on a fresh Debian Stretch setup, so no MySQL server installed...I spent some time poking around and it's definitely the the `debconf-set-selections` which fails. But, I haven't solved yet why...could be a Debian issue. I'll get a VM setup w/Ubuntu to compare. 

```
markd@xps:~/dev$ sudo debconf-set-selections -v <<< 'mysql-server mysql-server/root_password string password root'
[sudo] password for markd: 
info: Trying to set 'mysql-server/root_password' [string] to 'password root'
info: Loading answer for 'mysql-server/root_password'
error: Cannot find a question for mysql-server/root_password
```

**Comment by mdrovdahl** [comment]
What a difference a day makes...resolved the `debconf-set-selections` error with below from https://askubuntu.com/a/408725

```
markd@xps:~/dev$ sudo /usr/share/debconf/fix_db.pl 
debconf: template "mysql-server/root_password" claims to be used by nonexistant question "mysql-server/root_password"; removing that.
debconf: template "mysql-server/root_password_again" claims to be used by nonexistant question "mysql-server/root_password_again"; removing that.
markd@xps:~/dev$ sudo debconf-set-selections -v <<< 'mysql-server mysql-server/root_password string password root'
info: Trying to set 'mysql-server/root_password' [string] to 'password root'
info: Loading answer for 'mysql-server/root_password'
```
