### ISSUE TITLE
Package 'mysql-client' has no installation candidate

### ISSUE THREAD

**Issue by Aeyzaz** [postlight/headless-wp-starter#220]
i am getting this errors while trying to build the container.

**Comment by hankroark** [comment]
I had the same issue.  Just submitted a pull request to resolve: https://github.com/postlight/headless-wp-starter/pull/221

**Comment by Aeyzaz** [comment]
I have resolved it using mysql-client-* in Dockerfile

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Aeyzaz** [comment]
But now the problem is, i am unable to access the containers from host and getting connection refused and timeout sometimes.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sonofalder** [comment]
I was able to get it working

change it to default-mysql-client, you may also want to change it to default-libmysqlclient-dev

**Comment by krishaamer** [comment]
Same problem here. Where to change it @sonofalder ?

**Comment by sonofalder** [comment]
> Same problem here. Where to change it @sonofalder ?
> 
> Answering myself, in the "Dockerfile".

What does your Dockerfile look like? You should just be able to update it to
RUN
apt-get install default-mysql-client
apt-get install default-libmysqlclient-dev

**Comment by alexiakl** [comment]
Fixed here: https://github.com/postlight/headless-wp-starter/pull/221

**Comment by ashleyr889** [comment]
I'm having the same issues
