### ISSUE TITLE
Cannot get frontend to work

### ISSUE THREAD

**Issue by hankroark** [postlight/headless-wp-starter#222]
[yarn.log](https://github.com/postlight/headless-wp-starter/files/3390169/yarn.log)

I've tried multiple times to get the frontend component to work.  Frontend-graphql works just fine.  I've uninstalled node, yarn, reinstalled....installed full version of xcode not just command line.  I'm kinda new to this area, so any help is appreciated.  I have attached the logs from running 'yarn' in the frontend directory.

**Comment by mcescalante** [comment]
`node-sass` is failing, same thing happening for me.

in `frontend/package.json` change the node-sass line (35) to `"node-sass": "^4.12.0",`. Running `yarn` followed by `yarn start` has the next.js frontend loading for me on localhost:3000

**Comment by operapreneur** [comment]
Confirming bumping the node-sass version fixed the build error for me as well. 
`"node-sass": "^4.12.0"`

**Comment by alexiakl** [comment]
Fixed here: https://github.com/postlight/headless-wp-starter/pull/221
