### ISSUE TITLE
Unable to login via site

### ISSUE THREAD

**Issue by alexwasner** [postlight/headless-wp-starter#233]
I am able to login with `nedstark` / `winteriscoming` as well as a user I just created, but when on the `:3000` / `:3001`, I am unable to login from the `/login` page. Both urls just say `Login - Sorry, that username and password combination is not valid.`

**Comment by magidmroueh** [comment]
@alexwasner  There was an issue with dependencies that was resolved in the following merged [PR](https://github.com/postlight/headless-wp-starter/pull/234)
after syncing your repo, if you still can’t login, please make sure to set the required secret keys: [REST & GraphQL JWT Authentication](https://github.com/postlight/headless-wp-starter#rest--graphql-jwt-authentication) section.
