### ISSUE TITLE
Postlight theme removed featured image from post

### ISSUE THREAD

**Issue by DavidKarasek** [postlight/headless-wp-starter#235]
When I have the theme enabled, I am not able to add featured images to my posts. When I switch to the default theme, it works fine.

**Comment by modelm** [comment]
I think it makes sense not to enable thumbnail support by default in a headless theme, but you can enable theme support for thumbnails by adding this to the theme functions.php:

    add_theme_support( 'post-thumbnails' );

https://developer.wordpress.org/themes/functionality/featured-images-post-thumbnails/

**Comment by egdavid** [comment]
Disabling thumbnail doesn't make sense to me since it's possible to retreive featured images through the API requests.
Here is a taste of what I've done to achieve that.

```
add_action('rest_api_init', 'register_rest_images', 15);

function register_rest_images()
{
    register_rest_field(
        array('post'),
        'fimg_url',
        array(
            'get_callback'    => 'get_rest_featured_image',
            'update_callback' => null,
            'schema'          => null,
        )
    );
}
function get_rest_featured_image($object, $field_name, $request)
{
    if ($object['featured_media']) {
        $img = wp_get_attachment_image_src($object['featured_media'], 'app-thumb');
        return $img[0];
    }
    return false;
}
```
