### ISSUE TITLE
Port issues

### ISSUE THREAD

**Issue by bkyam** [postlight/headless-wp-starter#242]
Let me preface this with how incredible this starter kit seems to be, and that I am relatively new to docker containers, in that I've only worked on one application in containers before.

I'm having a difficult time getting this package to start up wordpress.  I've made no modifications to the configs. When I run 'docker-compose up -d', all seems well. When I cd to 'frontend' and 'yarn && yarn start' I'm running into a port conflict, 'Error: listen EADDRINUSE :::3000'.

I have no other servers running on my box, and I've reset my docker desktop to delete all containers. I've done the later step multiple times.

I know this is not a lot of info, but has anyone else run into these issues?

**Comment by CurtisBelt** [comment]
Try running some commands to detect what could be running on port 3000.

On Linux for example `sudo netstat -pntl | grep 3000`.
On Mac try this https://stackoverflow.com/a/4421674 and don't forget to also try them with sudo.

**Comment by bkyam** [comment]
@CurtisBelt Thank you for that

When no servers are running, then nothing is listening to port 3000.

When I run the 'docker-compose up -d' command, and rebuild the containers, then Docker itself is listening to port 3000.  I know this from running 'lsof'.

```
com.docke 96133 myuser   23u  IPv6 0xae090177f3b4d1eb      0t0  TCP *:3000 (LISTEN)
```

This is *before* I run yarn in the frontend directory.

Then if I cd into 'frontend' and run yarn && yarn start, here's the output:
```
$yarn && yarn start
yarn install v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > babel-loader@8.0.6" has unmet peer dependency "@babel/core@^7.0.0".
warning " > eslint-config-airbnb@18.0.1" has incorrect peer dependency "eslint-plugin-react-hooks@^1.7.0".
[4/4] 🔨  Building fresh packages...
✨  Done in 5.86s.
yarn run v1.19.1
$ CHOKIDAR_USEPOLLING=true node server.js
[ ready ] compiled successfully
[ wait ]  compiling ...
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at Function.listen (/Users/bkaplan/Sites/yamww-intranet/frontend/node_modules/express/lib/application.js:618:24)
    at app.prepare.then (/Users/bkaplan/Sites/yamww-intranet/frontend/server.js:42:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
```

If I run the lsof command again to see what's listening to port 3000, I get the same output.

**Comment by bkyam** [comment]
I'm pretty sure the issue is Docker Desktop. I ran another application that runs on 3000, and ran into the same exact error. Then I turned off Docker Desktop, and that application was able to run.

**Comment by CurtisBelt** [comment]
Yeah, sorry I'm on Fedora and don't have a mac, I'm unable to reproduce, so that makes sense since I don't use Docker Desktop.
