### ISSUE TITLE
feat: make API endpoint configurable

### ISSUE THREAD

**Issue by ginatrapani** [postlight/headless-wp-starter#26]
Currently in the frontend JS, `localhost:8080` is hardcoded as the API endpoint. Let's make this configurable as a buildtime/runtime environment variable.

**Comment by alexmanno** [comment]
Created PR here #27 enjoy!

**Comment by ginatrapani** [comment]
Closed in 7bf7f9aaf54ac0e0756f50b7f06f78ae943fe612
