### ISSUE TITLE
fix: use getInitialProps in Header.js

### ISSUE THREAD

**Issue by ginatrapani** [postlight/headless-wp-starter#31]
Instead of state, to render the header menu.

**Comment by webwelten** [comment]
`getInitialProps` won't work in Header.js because it's not supported in nested components.
It could be done in index.js though.

**Comment by kevinlangleyjr** [comment]
Or even better, wrap the pages in a HOC to get the data for all pages.

**Comment by tyler-barnes** [comment]
#41 addresses this.
