### ISSUE TITLE
[meta]: Project status?

### ISSUE THREAD

**Issue by montchr** [postlight/headless-wp-starter#340]
Is this project still maintained?

While considering using this template, I'm seeing a few indications that give me pause:

- #202 indicates (I think) an unusable Docker container from a fresh install, and yet there's been no response from maintainers since 2019
- As of this writing, the most recent commit was in mid-March 2022 
- Backlog of pull requests, most of which are automated `npm` dependency updates (I think those could be configured to be merged automatically)
- Some user-submitted pull requests for bug fixes, feature improvements, and even documentation suggestions ignored without comment for years

**Comment by mcorrello** [comment]
Yes this project is still being maintained. We’ve recently gone through and updated some of the dependencies and PR backlog. The latest version should be working from a fresh install. 

If you run into any issues please raise an issue or PR.
