### ISSUE TITLE
Can't get up & running on mac

### ISSUE THREAD

**Issue by LukeSmetham** [postlight/headless-wp-starter#35]
When installing the wordpress portion of the repo with 

`yarn install && yarn start`

I seem to get a lot of errors as below
` [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e 'create user if not exists wp_headless'
sh: mysql: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e 'create database if not exists wp_headless'
sh: mysql: command not found
 [Exec]  Exit code 127  Time 0.003s
 [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e "grant all privileges on wp_headless . * to wp_headless@localhost identified by 'wp_headless'"
sh: mysql: command not found
 [Exec]  Exit code 127  Time 0.003s
 [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e 'flush privileges'
sh: mysql: command not found
 [Exec]  Exit code 127  Time 0.003s
 [Exec] Running wp core download --version=4.9 --locale=en_US --force in /Users/lukesmetham/Sites/arkitek-wp/wordpress
Downloading WordPress 4.9 (en_US)...
Using cached file '/Users/lukesmetham/.wp-cli/cache/core/wordpress-4.9-en_US.tar.gz'...
Success: WordPress downloaded.
 [Exec] Done in 1.079s
 [Exec] Running wp core config --dbname=wp_headless --dbuser=wp_headless --dbpass=wp_headless --dbhost=0.0.0.0 in /Users/lukesmetham/Sites/arkitek-wp/wordpress
env: mysql: No such file or directory
 [Exec]  Exit code 127  Time 0.226s
 [Exec] Running wp db drop --yes in /Users/lukesmetham/Sites/arkitek-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.247s
 [Exec] Running wp db create --yes in /Users/lukesmetham/Sites/arkitek-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.213s
 [Exec] Running wp core install --url=localhost:8080 --title="Postlight Headless WP Starter" --admin_user="nedstark" --admin_password="winteriscoming" --admin_email="nedstark@headlesswpstarter.dev" --skip-email in /Users/lukesmetham/Sites/arkitek-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.205s
 [Exec] Running wp theme activate postlight-headless-wp in /Users/lukesmetham/Sites/arkitek-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.201s
 [Exec] Running wp theme delete twentyfourteen in /Users/lukesmetham/Sites/arkitek-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.266s
 [Exec] Running wp theme delete twentyfifteen in /Users/lukesmetham/Sites/arkitek-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.308s
 [Exec] Running wp theme delete twentysixteen in /Users/lukesmetham/Sites/arkitek-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.26s
 [Exec] Running wp theme delete twentyseventeen in /Users/lukesmetham/Sites/arkitek-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.227s
 [Exec] Running wp plugin delete akismet in /Users/lukesmetham/Sites/arkitek-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.227s
 [Exec] Running wp plugin delete hello in /Users/lukesmetham/Sites/arkitek-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.256s
 [Exec] Running wp plugin activate acf-to-wp-api advanced-custom-fields-pro akismet custom-post-type-ui wp-migrate-db-pro wp-migrate-db-pro-cli wp-migrate-db-pro-media-files wp-rest-api-v2-menus in /Users/lukesmetham/Sites/arkitek-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.277s
 [Exec] Running wp acf sync in /Users/lukesmetham/Sites/arkitek-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.294s
 [Exec] Running wp rewrite structure "/%year%/%monthnum%/%day%/%postname%/" in /Users/lukesmetham/Sites/arkitek-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.205s`

Then once it completes if I go to localhost:8080 I get the standard WP install screen asking for language and database config, any help would be massivley appreciated, I've been dying for something like this for a long time!

**Comment by george-haddad** [comment]
Hi there, it looks like it is trying to look for the MySQL command and not finding it

`sh: mysql: command not found [Exec] Exit code 127`

Can we have  more info on your current setup like the following would be helpful:
1. Version of Mac OS
2. Is MySQL already installed?

**Comment by LukeSmetham** [comment]
Hey, thanks for the quick reply! 

My MacOS version is 10.11.6 (15G1611)

Thinking about it (and now feeling slightly stupid), I don't think MySQL is installed, I will do that now and report back

**Comment by george-haddad** [comment]
Actually `yarn install` is supposed to install mysql for you and get it up and running. I'm thinking maybe it wasn't able to install it or had some issue doing so.

Was there more output in the logs?

**Comment by LukeSmetham** [comment]
I tried manually installing and still no change,
Heres the full output in my terminal
`Lukes-iMac:ark-wp lukesmetham$ yarn install
yarn install v0.21.3
$ chmod +x install.sh && ./install.sh
Warning: homebrew/php/wp-cli 1.4.1 is already installed
Warning: homebrew/php/robo 1.1.1 is already installed
Warning: mysql 5.7.20 is already installed, it's just not linked.
You can use `brew link mysql` to link this version.
./install.sh: line 28: mysql.server: command not found
./install.sh: line 30: mysql: command not found
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ robo wordpress:setup

 This will replace your current WordPress install. Are you sure you want to do this? (yes/no) [no]:
 > yes

 [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e 'create user if not exists wp_headless'
sh: mysql: command not found
 [Exec]  Exit code 127  Time 0.004s
 [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e 'create database if not exists wp_headless'
sh: mysql: command not found
 [Exec]  Exit code 127  Time 0.003s
 [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e "grant all privileges on wp_headless . * to wp_headless@localhost identified by 'wp_headless'"
sh: mysql: command not found
 [Exec]  Exit code 127  Time 0.003s
 [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e 'flush privileges'
sh: mysql: command not found
 [Exec]  Exit code 127  Time 0.003s
 [Exec] Running wp core download --version=4.9 --locale=en_US --force in /Users/lukesmetham/Sites/ark-wp/wordpress
Downloading WordPress 4.9 (en_US)...
Using cached file '/Users/lukesmetham/.wp-cli/cache/core/wordpress-4.9-en_US.tar.gz'...
Success: WordPress downloaded.
 [Exec] Done in 4.348s
 [Exec] Running wp core config --dbname=wp_headless --dbuser=wp_headless --dbpass=wp_headless --dbhost=0.0.0.0 in /Users/lukesmetham/Sites/ark-wp/wordpress
env: mysql: No such file or directory
 [Exec]  Exit code 127  Time 0.196s
 [Exec] Running wp db drop --yes in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.185s
 [Exec] Running wp db create --yes in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.19s
 [Exec] Running wp core install --url=localhost:8080 --title="Postlight Headless WP Starter" --admin_user="nedstark" --admin_password="winteriscoming" --admin_email="nedstark@headlesswpstarter.dev" --skip-email in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.184s
 [Exec] Running wp theme activate postlight-headless-wp in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.187s
 [Exec] Running wp theme delete twentyfourteen in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.191s
 [Exec] Running wp theme delete twentyfifteen in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.181s
 [Exec] Running wp theme delete twentysixteen in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.183s
 [Exec] Running wp theme delete twentyseventeen in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.185s
 [Exec] Running wp plugin delete akismet in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.191s
 [Exec] Running wp plugin delete hello in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.182s
 [Exec] Running wp plugin activate acf-to-wp-api advanced-custom-fields-pro akismet custom-post-type-ui wp-migrate-db-pro wp-migrate-db-pro-cli wp-migrate-db-pro-media-files wp-rest-api-v2-menus in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.182s
 [Exec] Running wp acf sync in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.184s
 [Exec] Running wp rewrite structure "/%year%/%monthnum%/%day%/%postname%/" in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.182s
 [Exec] Running wp option update blogdescription "Just another (headless) WordPress site by your friends at Postlight" in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.191s
 [Exec] Running wp post update 1 wp-content/themes/postlight-headless-wp/post-content/sample-post.txt --post_title="Sample Post" --post_name=sample-post in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.195s
 [Exec] Running wp post create wp-content/themes/postlight-headless-wp/post-content/welcome.txt --post_type=page --post_status=publish --post_name=welcome --post_title="Congratulations!" in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.183s
 [Exec] Running wp term update category 1 --name="Sample Category" in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.186s
 [Exec] Running wp menu create "Header Menu" in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.181s
 [Exec] Running wp menu item add-post header-menu 1 in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.184s
 [Exec] Running wp menu item add-post header-menu 2 in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.186s
 [Exec] Running wp menu item add-term header-menu category 1 in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.181s
 [Exec] Running wp menu item add-custom header-menu "Read about the Starter Kit on Medium" https://trackchanges.postlight.com/introducing-postlights-wordpress-react-starter-kit-a61e2633c48c in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.187s
 [Exec] Running wp menu location assign header-menu header-menu in /Users/lukesmetham/Sites/ark-wp/wordpress
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
 [Exec]  Exit code 1  Time 0.248s`

**Comment by LukeSmetham** [comment]
then underneath that was "[OK] Great. you can now log into... etc."

**Comment by george-haddad** [comment]
OK I think we found the culprit in this message

`Warning: mysql 5.7.20 is already installed, it's just not linked. You can use brew link mysql to link this version.`

I'm not a Mac OS use my self but I found this post on stackoverflow that resolved the issue for someone having the exact same problem. https://stackoverflow.com/questions/12812613/brew-link-mysql-did-not-complete

Could you follow the instructions on that post and try the installation again. I guess to try the install from a clean slate.

**Comment by LukeSmetham** [comment]
All Fixed!! 
Thanks so much for your help, can't wait to get playing with this 👌

**Comment by george-haddad** [comment]
:+1: alright that's great, happy to help.
