### ISSUE TITLE
Help getting this running on now.sh

### ISSUE THREAD

**Issue by ericmasiello** [postlight/headless-wp-starter#36]
Hi, in the original blog post https://trackchanges.postlight.com/introducing-postlights-wordpress-react-starter-kit-a61e2633c48c, you mentioned being able to run this on now.sh. Any tips on making that work?

When I attempt to run `now` from the root directory, I get the following output:

```
12/11 08:04 AM (12m)
npm install
12/11 08:04 AM (12m)
✓ Using "yarn.lock"
12/11 08:04 AM (12m)

> headless-wp-starter@1.0.0 preinstall /home/nowuser/src
> chmod +x install.sh && ./install.sh
12/11 08:04 AM (12m)

Sorry, this installation script only works on Mac OS X and Ubuntu Linux. Looks like your operating system is linux-musl.
```

**Comment by ginatrapani** [comment]
Hi @ericmasiello - you can't run WordPress on Now, but you can run the frontend on Now. Your WordPress installation would have to be elsewhere and publicly accessible, and it would require changes on the frontend to talk to that publicly accessible WordPress URL. If you `cd frontend`, you could run Now and choose whether to just deploy the Next.js app, or the Docker container to Now.

**Comment by ericmasiello** [comment]
Ah okay! I must have misunderstood. Thanks @ginatrapani
