### ISSUE TITLE
babel-loader -  You may need an appropriate loader to handle this file type. 

### ISSUE THREAD

**Issue by BenjaminBeguin** [postlight/headless-wp-starter#39]
Hey guys,

I'm trying something very basic, to import a css file in a component like this : 
import './style.css' 
The file style.css exist and is in the same folder as the component js file. 
I already did that in other react web app but first time using the headless-wp-starter. 

I get this error : 

![image](https://user-images.githubusercontent.com/12866555/34264385-0d65243a-e673-11e7-8b8c-d1d681932770.png)

Any idea ? 

Most of the fix for this issue that i found is to custum the babel loader but i didn't how to do that with this starter 'cause there is no webpack.babel.config.js or something like this

**Comment by ginatrapani** [comment]
Hey @BenjaminBeguin we just added support for Sass -- try using styles this way: https://github.com/postlight/headless-wp-starter/commit/ed36ea18706ef7142668c910bcea89019644d7ca
