### ISSUE TITLE
API POST request Unauthorized

### ISSUE THREAD

**Issue by LouisJackson** [postlight/headless-wp-starter#40]
I tried and create a WP User in the React structure using WP REST API endpoints. I get an Unauthorized 401 Error Code. See screenshot below.

<img width="501" alt="capture d ecran 2017-12-22 a 01 16 48" src="https://user-images.githubusercontent.com/8021023/34280159-0cbf3410-e6b6-11e7-870c-0feee31561b0.png">

Why is this happening? How to fix it?

Thanks.

**Comment by ginatrapani** [comment]
Hi there -- When I try this request I also get "Sorry, you are not allowed to create new users." I think that's because create user has to be an authenticated request. https://code.tutsplus.com/tutorials/wp-rest-api-setting-up-and-using-basic-authentication--cms-24762
