### ISSUE TITLE
404 when hitting refresh

### ISSUE THREAD

**Issue by klase** [postlight/headless-wp-starter#52]
After getting everything up and running, I get a 404 on every page after I hit refresh and server rendering kicks in. The console gives me the following error (in this case on the sample page):

Page does not exist: /page/sample-page
Error: Page does not exist: /page/sample-page

**Comment by ovidiu-balau** [comment]
How did you fix this?

**Comment by klase** [comment]
Just make sure to start the dev npm script which starts the custom express server where the routes are defined instead of the default npm script which just runs next start.

**Comment by ovidiu-balau** [comment]
That fixed it!
