### ISSUE TITLE
Routing works fine in dev but not in live mode

### ISSUE THREAD

**Issue by Radzam** [postlight/headless-wp-starter#55]
Thank you for your great work!

Its working fine when in dev mode ( `yarn run dev` )but I discovered once you deploy it (try with `yarn run build` and `yarn run start`), you can route to pages but 2 critical errors happen.

1) the styling doesn't follow along on those pages.
2) if you refresh on that url (or try to visit it), then you hit a 404 error. 

Could you please help me figure this out? I tried with a fresh install and deploying to now and its the same in all scenarios.

**Comment by Radzam** [comment]
I manage to solve issue 2) by changing start script from `"start": next start`to `"start": "NODE_ENV=production node server.js",` however the problem remains where styles dont get applied when routing, only on the initial loading page or when refreshing a page, but routing to a new page or back to it strips off all the styling, really strange. Anyone that can help me solve it?

**Comment by mantagen** [comment]
@Radzam it is standard practice when running a 'live' node server, to run it with an environment variable NODE_ENV=production :) Node hosting solutions such as Heroku do this for you

**Comment by Radzam** [comment]
@mantagen thank you for the answer but Ive done that. The problem I am experiencing is that the styling doesnt get applied when routing pages with the current setup and i cant figure out what it causing that. I tried with both styled jsx and sass

**Comment by ginatrapani** [comment]
Superseded by #56
