### ISSUE TITLE
Frontend: CSS does not get applied when routing

### ISSUE THREAD

**Issue by Radzam** [postlight/headless-wp-starter#56]
Styles don't get applied when routing to other pages that are styled, tried with both styled jsx and sass. I also tried with a fresh isntall, same thing there. Anyone that can look into it please?

**Comment by tristanoneil** [comment]
@Radzam I was unable to reproduce, is this still an issue for you?

**Comment by modelm** [comment]
If anybody can reproduce this feel free to re-open.
