### ISSUE TITLE
Ubuntu/Windows error starting backend: No such file or directory in /tmp/wp-cli-router.php

### ISSUE THREAD

**Issue by jrdubina** [postlight/headless-wp-starter#58]
Hello,

I have been getting the following error when i attempt to yarn start.

`PHP Warning:  require_once(index.php): failed to open stream: No such file or directory in /tmp/wp-cli-router.php on line 111`

`PHP Fatal error:  require_once(): Failed opening required 'index.php' (include_path='.:/usr/share/php') in /tmp/wp-cli-router.php on line 111`

I am using Ubuntu on Windows.

Any Idea why I would get this error?

**Comment by jrdubina** [comment]
Here is my whole log of when I do yarn install && yarn start

$ sudo yarn install && sudo yarn start --allow-root
[sudo] password for jrdubina:
yarn install v1.5.1
$ chmod +x install.sh && ./install.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
mysql-server is already the newest version (5.7.21-0ubuntu0.16.04.1).
The following packages were automatically installed and are no longer required:
  gyp libfreetype6 libjs-inherits libjs-node-uuid libjs-underscore libuv1 libuv1-dev node-abbrev node-ansi
  node-ansi-color-table node-archy node-async node-block-stream node-combined-stream node-cookie-jar
  node-delayed-stream node-forever-agent node-form-data node-fstream node-fstream-ignore node-github-url-from-git
  node-glob node-graceful-fs node-gyp node-inherits node-ini node-json-stringify-safe node-lockfile node-lru-cache
  node-mime node-minimatch node-mkdirp node-mute-stream node-node-uuid node-nopt node-normalize-package-data
  node-npmlog node-once node-osenv node-qs node-read node-read-package-json node-request node-retry node-rimraf
  node-semver node-sha node-sigmund node-slide node-tar node-tunnel-agent node-underscore node-which
  python-pkg-resources
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 115 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
php is already the newest version (1:7.0+35ubuntu6.1).
php-mysql is already the newest version (1:7.0+35ubuntu6.1).
The following packages were automatically installed and are no longer required:
  gyp libfreetype6 libjs-inherits libjs-node-uuid libjs-underscore libuv1 libuv1-dev node-abbrev node-ansi
  node-ansi-color-table node-archy node-async node-block-stream node-combined-stream node-cookie-jar
  node-delayed-stream node-forever-agent node-form-data node-fstream node-fstream-ignore node-github-url-from-git
  node-glob node-graceful-fs node-gyp node-inherits node-ini node-json-stringify-safe node-lockfile node-lru-cache
  node-mime node-minimatch node-mkdirp node-mute-stream node-node-uuid node-nopt node-normalize-package-data
  node-npmlog node-once node-osenv node-qs node-read node-read-package-json node-request node-retry node-rimraf
  node-semver node-sha node-sigmund node-slide node-tar node-tunnel-agent node-underscore node-which
  python-pkg-resources
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 115 not upgraded.
--2018-04-02 10:46:55--  https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.196.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.196.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4561899 (4.3M) [application/octet-stream]
Saving to: ‘wp-cli.phar’

wp-cli.phar                   100%[=================================================>]   4.35M  12.1MB/s    in 0.4s

2018-04-02 10:46:57 (12.1 MB/s) - ‘wp-cli.phar’ saved [4561899/4561899]

--2018-04-02 10:46:57--  http://robo.li/robo.phar
Resolving robo.li (robo.li)... 104.27.148.169, 104.27.149.169, 2400:cb00:2048:1::681b:94a9, ...
Connecting to robo.li (robo.li)|104.27.148.169|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://robo.li/robo.phar [following]
--2018-04-02 10:46:57--  https://robo.li/robo.phar
Connecting to robo.li (robo.li)|104.27.148.169|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2415523 (2.3M) [application/octet-stream]
Saving to: ‘robo.phar’

robo.phar                     100%[=================================================>]   2.30M  4.64MB/s    in 0.5s

2018-04-02 10:47:00 (4.64 MB/s) - ‘robo.phar’ saved [2415523/2415523]

 * Starting MySQL database server mysqld                                                                                No directory, logging in with HOME=/
                                                                                                                 [ OK ]
[1/4] Resolving packages...
success Already up-to-date.
$ robo wordpress:setup

 This will replace your current WordPress install. Are you sure you want to do this? (yes/no) [no]:
 > no

Done in 34.64s.
yarn run v1.5.1
$ wp server --allow-root
PHP 7.0.28-0ubuntu0.16.04.1 Development Server started at Mon Apr  2 10:47:30 2018
Listening on http://127.0.0.1:8080
Document root is /home/jrdubina/wordpress
Press Ctrl-C to quit.
[Mon Apr  2 10:47:37 2018] PHP Warning:  require_once(index.php): failed to open stream: No such file or directory in /tmp/wp-cli-router.php on line 111
[Mon Apr  2 10:47:37 2018] PHP Fatal error:  require_once(): Failed opening required 'index.php' (include_path='.:/usr/share/php') in /tmp/wp-cli-router.php on line 111

**Comment by ginatrapani** [comment]
@jrdubina If you answer "yes" to "This will replace your current WordPress install. Are you sure you want to do this? (yes/no)" what does that output look like?

**Comment by jrdubina** [comment]
@ginatrapani 

[Exec] Running mysql -uroot -proot -h 0.0.0.0 -e 'create user if not exists wp_headless'
mysql: [Warning] Using a password on the command line interface can be insecure.
 [Exec] Done in 0.194s
 [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e 'create database if not exists wp_headless'
mysql: [Warning] Using a password on the command line interface can be insecure.
 [Exec] Done in 0.171s
 [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e "grant all privileges on wp_headless . * to wp_headless@localhost identified by 'wp_headless'"
mysql: [Warning] Using a password on the command line interface can be insecure.
 [Exec] Done in 0.187s
 [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e 'flush privileges'
mysql: [Warning] Using a password on the command line interface can be insecure.
 [Exec] Done in 0.189s
 [Exec] Running wp core download --version=4.9.2 --locale=en_US --force in /home/jrdubina/headless/wordpress
Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress install exists under.

If you REALLY mean to run this as root, we won't stop you, but just bear in mind that any code on this site will then have full control of your server, making it quite DANGEROUS.

If you'd like to continue as root, please run this again, adding this flag:  --allow-root

If you'd like to run it as the user that this site is under, you can run the following to become the respective user:

    sudo -u USER -i -- wp <command>


 [Exec]  Exit code 1  Time 2.353s



and so on for the following. I have attempted to run this as root and under the user name and I get the errors either way.

**Comment by ginatrapani** [comment]
Hmm, nothing there looks off.... I don't have a Ubuntu setup handy to try to reproduce this on. I'll mark this as help wanted and see if I can repro this.

**Comment by george-haddad** [comment]
Hi there. I just tested a clean install on Ubuntu Subsystem on Windows and everything works as expected.

@jrdubina correct me if I am mistaken here, you answered `no` to the part of the installation where it asks you about replacing your current WordPress install?

Also from your install log I see the commands

`$ sudo yarn install && sudo yarn start --allow-root` 

These are not standard to the installation. Are these your commands?

Normally all that is needed is to run

`yarn install && yarn start` in the directory of `headless-wp-starter` . The install script `install.sh` already does some `sudo`ing for you none of which include the commands above. I have a feeling that running yarn under root is probably causing this; and stating `no` to the wordpress install part.

**Comment by george-haddad** [comment]
@jrdubina are you still getting errors related to this issue?
