### ISSUE TITLE
New feature: Configurable environment URLs

### ISSUE THREAD

**Issue by jcutrell** [postlight/headless-wp-starter#62]
Allowing configurable URLs for production/development environments using something like `dotenv` could help a ton, specifically when deploying the applications. A few hardcoded `localhost` URLs are still in place.

**Comment by glrodasz** [comment]
@jcutrell It will nice have it built-in but I think something like this could work, installing `dotenv`.

```	
require('dotenv').config()

export const Config = {
  wordpressUrl: proccess.env.WORDPRESS_URL || 'http://localhost:8080',
  apiUrl: proccess.env.API_URL || 'http://localhost:5000'
};
```

Note: I have changed `apiUrl` for `wordpressUrl` in this example because I have an api proxy and it has more sense for me, but you get the idea.

**Comment by modelm** [comment]
implemented in https://github.com/postlight/headless-wp-starter/blob/feat-dockerer/.env
