### ISSUE TITLE
Robo no longer on brew; update install.sh

### ISSUE THREAD

**Issue by richTheCreator** [postlight/headless-wp-starter#65]
Ran install, then...

`ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)`

**Debugged for hrs.** I was convinced it was the mysql install and it seemed so because it would not run with out `mysqld --skip-grant-tables`.

 However once I did manage to get it to run `localhost:8080/wp-admin/` threw an error:
 `Warning: require_once(index.php): failed to open stream: No such file or directory in /private/var/folders/ss/k91_63kd68vdbby1c038f4z00000gp/T/wp-cli-router.php on line 111`

I began to uninstall all deps from the `install.sh`. This is when I noticed that `homebrew/php/robo` was not installed at all. After some researching I found that the formula had been deprecated on brew and is only avail as direct download and install from [robo](https://robo.li/). 

**Note:** In order to install the `robo.phar` on my mac I did hold `cmd + r` at boot time and launch the terminal then run  `csrutil disable` and reboot. Other wise moving the robo file to usr/bin was denied by the OS.

Hope this saves others some time & hopefully you can update the `install.sh`.

**Comment by addijhaq** [comment]
@richTheCreator not good to disable csrutil. best is to modify the instructions on robo website from 
```sudo chmod +x robo.phar && mv robo.phar /usr/bin/robo```
to 
```sudo chmod +x robo.phar && mv robo.phar /usr/local/bin/robo```
