### ISSUE TITLE
localhost:8000/wp-admin leads to WP installation instead of the dashboard

### ISSUE THREAD

**Issue by kilinkis** [postlight/headless-wp-starter#66]
First of all, thanks for your efforts, this is a great project.

so, when I echo $PATH:
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

still, mysql commands seems to be pointing somewhere else.
FYI: I got MAMP installed but not running

when I run: yarn install && yarn start
I can access localhost:8000/wp-admin, but leads me to the WP installation instead of the dashboard.

when running that command, I see the error stated on the the Troubleshooting tier in the readme file:

```
Warning: mysql 5.7.21 is already installed and up-to-date
...
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```

I tried the solutions suggested there, but still have the same problem.
My ~/.bash_profile file doesn't add anything to the PATH variable, and I followed the steps listed here: 
https://coderwall.com/p/os6woq/uninstall-all-those-broken-versions-of-mysql-and-re-install-it-with-brew-on-mac-mavericks

I'm stuck after that, don't know what else to try.

any ideas? thanks!

**Comment by richTheCreator** [comment]
did you run `mysql_secure_installation`?

**Comment by kilinkis** [comment]
hi @richTheCreator, I hadn't. I just did, and chose pretty much all the insecure options (this is just for local development).

Still I see the same error :/

**Comment by ginatrapani** [comment]
Hi there -- it sounds like the database username and password isn't set. I just merged support for adding those in yourself during `yarn install`. Pull the latest master and give it a try.

**Comment by kilinkis** [comment]
Thank you @ginatrapani!
