### ISSUE TITLE
Backend Wordpress: Starting up Wordpress Backend getting error Messages.

### ISSUE THREAD

**Issue by brandonpowell** [postlight/headless-wp-starter#71]
I'm just started working with **postlight**  getting this error whenever I start up the WP server. I might have missed a step. Could someone guide me step by step through the repo an again sometimes miss leading?  [`@#`](url)
 
__________________________________________________________________________________________________________

```invalid json response body at http://localhost:8080/wp-json/menus/v1/menus/header-menu reason: Unexpected token < in JSON at position 0

FetchError: invalid json response body at http://localhost:8080/wp-json/menus/v1/menus/header-menu reason: Unexpected token < in JSON at position 0
    at /Users/brandonpowell/headless-wp-starter/frontend/node_modules/node-fetch/lib/body.js:48:31 
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)```




```Warning: require_once(index.php): failed to open stream: No such file or directory in /private/var/folders/62/rvytymts561_lt66mbcb_c7m0000gn/T/wp-cli-router.php on line 111

Fatal error: require_once(): Failed opening required 'index.php' (include_path='.:') in /private/var/folders/62/rvytymts561_lt66mbcb_c7m0000gn/T/wp-cli-router.php on line 111```




```Not Found
The requested resource / was not found on this server.```

**Comment by ginatrapani** [comment]
Hi there,

When you visit http://localhost:8080/wp-admin/, what do you see?

Can you share everything that gets output in your terminal after you run `yarn install && yarn start` ?

**Comment by brandonpowell** [comment]
ok, @ginatrapani  

Hello three,

after I run: `yarn install && yarn start` 

```Warning: wp-cli 1.5.0 is already installed and up-to-date
To reinstall 1.5.0, run `brew reinstall wp-cli`
Error: No available formula with the name "homebrew/php/robo"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
Warning: mysql 5.7.21 is already installed and up-to-date
To reinstall 5.7.21, run `brew reinstall mysql`
Starting MySQL
 SUCCESS!
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ robo wordpress:setup
sh: robo: command not found
error An unexpected error occurred: "Command failed.
Exit code: 127
Command: sh
Arguments: -c robo wordpress:setup
Directory: /Users/brandonpowell/headless-wp-starter
Output:
".
info If you think this is a bug, please open a bug report with the information provided in"/Users/brandonpowell/headless-wp-starter/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.```

**Comment by brandonpowell** [comment]
When I run front-end of react:

``` DONE  Compiled successfully in 34107ms            21:27:20

> Ready on http://localhost:3000
> Building page: /


 DONE  Compiled successfully in 54370ms            21:29:51



 WAIT  Compiling...                                21:29:56

{ FetchError: invalid json response body at http://localhos
t:8080/wp-json/menus/v1/menus/header-menu reason: Unexpecte
d token < in JSON at position 0
    at /Users/brandonpowell/headless-wp-starter/frontend/no
de_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js
:188:7)
  name: 'FetchError',
  message: 'invalid json response body at http://localhost:
8080/wp-json/menus/v1/menus/header-menu reason: Unexpected
token < in JSON at position 0',
  type: 'invalid-json' }


 DONE  Compiled successfully in 575ms              21:29:57

{ FetchError: invalid json response body at http://localhos
t:8080/wp-json/menus/v1/menus/header-menu reason: Unexpecte
d token < in JSON at position 0
    at /Users/brandonpowell/headless-wp-starter/frontend/no
de_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js
:188:7)
  name: 'FetchError',
  message: 'invalid json response body at http://localhost:
8080/wp-json/menus/v1/menus/header-menu reason: Unexpected
token < in JSON at position 0',
  type: 'invalid-json' }
{ FetchError: invalid json response body at http://localhost:8080/wp-json/menus/v1/menus/header-menureason: Unexpected token < in JSON at position 0
    at /Users/brandonpowell/headless-wp-starter/frontend/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'FetchError',
  message: 'invalid json response body at http://localhost:8080/wp-json/menus/v1/menus/header-menu reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }
{ FetchError: invalid json response body at http://localhost:8080/wp-json/menus/v1/menus/header-menureason: Unexpected token < in JSON at position 0
    at /Users/brandonpowell/headless-wp-starter/frontend/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'FetchError',
  message: 'invalid json response body at http://localhost:8080/wp-json/menus/v1/menus/header-menu reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }```

**Comment by ginatrapani** [comment]
Hi there! So here's the problem:

> sh: robo: command not found

Robo is required for the WordPress installation to complete. Robo used to be available on `brew` but it is no longer, so in b1dfe8c0a65ba22f41b35973daf5b1df31baf7b8 I updated the installation script to account for that.

Could you pull the latest state of the master branch, and try `yarn install && yarn start` again? This time, robo should get installed correctly.

**Comment by brandonpowell** [comment]
I want to make sure I find other error with package.json file. 
```Error: ENFILE: file table overflow, open '/Users/brandonpowell/headless-wp-starter/package.json'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at onUnexpectedError (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:89324:104)
    at /usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:89431:7
    at <anonymous>```

**Comment by ginatrapani** [comment]
@brandonpowell can you tell me more about this error? frontend or backend? Can you include the command you ran, and all the output that happened after that?

**Comment by vikaskyadav** [comment]
Hii @ginatrapani . I am stuck on setup-config screen 1 where I have to add the username, password, database name, prefix and hostname. I am using the credentials but It's not working at all. Any help I can get?

**Comment by justinchristensen66** [comment]
Hi, I am getting a similar problem.  I ran "yarn start" on the backend in the wordpress folder and when I went to the localhost:8080/wp-admin I got a white page with: 

Warning: require_once(index.php): failed to open stream: No such file or directory in /private/var/folders/r1/kn_16pb10jngr_s0w3lg734r0000gn/T/wp-cli-extract-from-phar-5ae9f4214ff026.00706502-router.php on line 111

Fatal error: require_once(): Failed opening required 'index.php' (include_path='.:') in /private/var/folders/r1/kn_16pb10jngr_s0w3lg734r0000gn/T/wp-cli-extract-from-phar-5ae9f4214ff026.00706502-router.php on line 111

yarn - 1.6
Homebrew 1.6.2

**Comment by ginatrapani** [comment]
Glad to hear that @justinchristensen66 !

**Comment by persephonepunch** [comment]
I am also getting the same white page error. How was this fixed?
Warning: require_once(index.php): failed to open stream: No such file or directory in /private/var/folders/p8/nhz8_lgs5ts529kdvwg07ypc0000gn/T/wp-cli-extract-from-phar-5afefa904cca84.73545066-router.php on line 111

Fatal error: require_once(): Failed opening required 'index.php' (include_path='.:') in /private/var/folders/p8/nhz8_lgs5ts529kdvwg07ypc0000gn/T/wp-cli-extract-from-phar-5afefa904cca84.73545066-router.php on line 111

**Comment by ThatKDB** [comment]
I'm getting the same error when visiting the frontend:

`invalid json response body at http://localhost:8080/wp-json/menus/v1/menus/header-menu reason: Unexpected token < in JSON at position 0

FetchError: invalid json response body at http://localhost:8080/wp-json/menus/v1/menus/header-menu reason: Unexpected token < in JSON at position 0
    at /mnt/e/headless-wp/headless-wp-starter/frontend/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`
Backend runs with no errors. 

This is running on Windows 10 1703 in WSL.

**Comment by persephonepunch** [comment]
I solved this by deleting an instance of MariaDB I was running. Great
product.

**Comment by fstepien** [comment]
@ginatrapani Can robo be installed manually for windows? I am getting the same error message as some of the posts above. Thanks. 

```
$ yarn install
yarn install v1.7.0
$ chmod +x install.sh && chmod +x mysql_config.sh && ./install.sh
[1/4] Resolving packages...
success Already up-to-date.
$ robo wordpress:setup
'robo' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by ThatKDB** [comment]
Everything seems to be working for me now. I did a `yarn install` again for both the `/wordpress` and `/frontend` folders and now everything seems to be as it should.

**Comment by ginatrapani** [comment]
> @ginatrapani Can robo be installed manually for windows? I am getting the same error message as some of the posts above. Thanks.

I think so? But I don't have a Windows machine here available to test. Give it a try and let us know how it goes.

**Comment by tristanoneil** [comment]
This issue no longer seems super actionable (a lot going on here). If anyone is still running into problems please open a new issue. Thanks!
