### ISSUE TITLE
Featured Image

### ISSUE THREAD

**Issue by doakheggeness** [postlight/headless-wp-starter#73]
There is no Featured Image metabox on the post edit/new page. This is included by default in WordPress. I tried adding 
'add_theme_support( 'post-thumbnails', array( 'post', 'page' ) );',

but the functions.php file would not update.

Is this a React thing?

Thanks,
Doak

**Comment by ginatrapani** [comment]
Hi there! If I add:

```php
add_theme_support( 'post-thumbnails', array( 'post', 'page' ) );
```

to the bottom of functions.php and then reload the post or page editor, I do see the Featured Image metabox in the admin. That should do it.
