### ISSUE TITLE
WordPress: Add sample field placeholders to the Headless Options page

### ISSUE THREAD

**Issue by glrodasz** [postlight/headless-wp-starter#75]
Hi, I just see a `Headless` item on the menu, but when I go there there is nothing, even if I have configured some Custom Fields groups.

![image](https://user-images.githubusercontent.com/1431663/39353542-a33fc9b6-49cd-11e8-908a-d131029fafed.png)

Regards

**Comment by brandonpowell** [comment]
I have you solve this issues already and I have same 
questions I well.

**Comment by ginatrapani** [comment]
Oh it's just an example placeholder of a Headless-specific options page, with no fields attached to it. I'll add some sample fields just to show off what's possible.

**Comment by glrodasz** [comment]
Sounds great!
