### ISSUE TITLE
Install fails when trying to create robo path  using  Linux Subsystem for Windows

### ISSUE THREAD

**Issue by baongit** [postlight/headless-wp-starter#77]
I'm using the Linux Subsystem for Windows and am unable to successfully install headless-wp-starter. I have followed repo instructions to the letter and installed latest version of yarn, nodejs, debconf-utils etc... , but still hangs when trying to create '/usr/bin/robo':

brent@PREC7710:/mnt/c/Users/brent/Desktop/headless-wp-starter$ yarn install
yarn install v1.6.0
$ chmod +x install.sh && ./install.sh
[sudo] password for brent:
Reading package lists... Done
Building dependency tree
Reading state information... Done
mysql-server is already the newest version (5.7.22-0ubuntu0.16.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
php is already the newest version (1:7.0+35ubuntu6.1).
php-mysql is already the newest version (1:7.0+35ubuntu6.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/brent/.wget-hsts'. HSTS will be disabled.
--2018-05-02 13:14:36--  https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
Resolving raw.githubusercontent.com... 151.101.184.133
Connecting to raw.githubusercontent.com|151.101.184.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4577919 (4.4M) [application/octet-stream]
Saving to: ‘wp-cli.phar’

wp-cli.phar                      100%[========================================================>]   4.37M  2.61MB/s    in 1.7s

2018-05-02 13:14:38 (2.61 MB/s) - ‘wp-cli.phar’ saved [4577919/4577919]

Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/brent/.wget-hsts'. HSTS will be disabled.
--2018-05-02 13:14:38--  http://robo.li/robo.phar
Resolving robo.li... 104.27.148.169, 104.27.149.169, 2400:cb00:2048:1::681b:94a9, ...
Connecting to robo.li|104.27.148.169|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://robo.li/robo.phar [following]
--2018-05-02 13:14:39--  https://robo.li/robo.phar
Connecting to robo.li|104.27.148.169|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2437686 (2.3M) [application/octet-stream]
Saving to: ‘robo.phar’

robo.phar                        100%[========================================================>]   2.32M  2.75MB/s    in 0.8s

2018-05-02 13:14:40 (2.75 MB/s) - ‘robo.phar’ saved [2437686/2437686]

mv: cannot create regular file '/usr/bin/robo': Permission denied
 * Starting MySQL database server mysqld
No directory, logging in with HOME=/
                                                                                                                           [ OK ]
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ robo wordpress:setup
/bin/sh: 1: robo: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

I noticed also that this created a robo.phar file and then on second attempt another robo.phar.1 file?

**Comment by george-haddad** [comment]
Yup, these were all errors that are fixed in this PR https://github.com/postlight/headless-wp-starter/pull/67

**Comment by baongit** [comment]
I made the changes to install.sh and RoboFile.php that were changed in feat-ask-for-db-root-pass branch and it's now working great :-)

Thank you!
