### ISSUE TITLE
Error: homebrew/php was deprecated. This tap is now empty as all its formulae were migrated.

### ISSUE THREAD

**Issue by willpmartin** [postlight/headless-wp-starter#89]
Getting the above error when running yarn install && yarn start. 

the full output is:

willmartin$ yarn install && yarn start
yarn install v1.6.0
$ chmod +x install.sh && ./install.sh
Warning: wp-cli 1.5.1 is already installed and up-to-date
To reinstall 1.5.1, run `brew reinstall wp-cli`
Error: homebrew/php was deprecated. This tap is now empty as all its formulae were migrated.
Warning: mysql 5.7.22 is already installed and up-to-date
To reinstall 5.7.22, run `brew reinstall mysql`
Starting MySQL
 SUCCESS! 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 5
Server version: 5.7.22 Homebrew

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 2018-05-19T18:27:45.6NZ mysqld_safe A mysqld process already exists

Any ideas?

**Comment by kevb10** [comment]
Have you tried removing and re-installing? Good place to start.

**Comment by seafoam6** [comment]
Same issue

**Comment by seafoam6** [comment]
reinstalling did not help in any way...........

**Comment by JasonZsl6** [comment]
Have you solved this problem

**Comment by tristanoneil** [comment]
It does not appear that `Error: homebrew/php was deprecated. This tap is now empty as all its formulae were migrated.` is actually the failure here (I think that's just a warning, even though it says it's an error). The installer should have been fixed in #105 please open a new issue with details if you're still having problems.
