### ISSUE TITLE
Frontend Setup for WPGraphQL?

### ISSUE THREAD

**Issue by baongit** [postlight/headless-wp-starter#91]
I see the WPGraphQL plugin has been added. Will there be any documentation on how to setup the frontend or is this ready?

The only thing I could find setting up GraphQL Client with Next.js:

https://github.com/zeit/next.js/tree/master/examples/with-apollo
https://github.com/GraphCMS/graphcms-examples/tree/master/next-apollo-blog

**Comment by ginatrapani** [comment]
Right now the API is being served, but the frontend isn't yet consuming it. Pull requests are welcome!

**Comment by baongit** [comment]
Thank you!
