### ISSUE TITLE
yarn install on MacOS not working

### ISSUE THREAD

**Issue by danboyle8637** [postlight/headless-wp-starter#94]
I've checked other issues. Found one that was similar but it provided no help. I am still unable to get my install to work properly. 

Here's what I get from terminal.

yarn install v1.7.0
$ chmod +x install.sh && chmod +x mysql_config.sh && ./install.sh
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
bat                         jenkins-job-builder         percona-server              teleport
fn                          libpqxx                     qmmp

==> Downloading https://github.com/wp-cli/wp-cli/releases/download/v1.5.1/wp-cli-1.5.1.phar
Already downloaded: /Users/danboyle/Library/Caches/Homebrew/wp-cli-1.5.1.phar
Error: SHA256 mismatch
Expected: c1114450e647ca0c72afcbb6d02b577a55ec9915a510399579626c960d5dd2d2
Actual: 0cc7a95e68a2ef02fc423614806c29a8e76e4ac8c9b3e67d6673635d6eaea871
Archive: /Users/danboyle/Library/Caches/Homebrew/wp-cli-1.5.1.phar
To retry an incomplete download, remove the file above.
Warning: wget 1.19.5 is already installed and up-to-date
To reinstall 1.19.5, run `brew reinstall wget`
--2018-05-31 19:48:09--  http://robo.li/robo.phar
Resolving robo.li (robo.li)... 104.27.148.169, 104.27.149.169
Connecting to robo.li (robo.li)|104.27.148.169|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://robo.li/robo.phar [following]
--2018-05-31 19:48:09--  https://robo.li/robo.phar
Connecting to robo.li (robo.li)|104.27.148.169|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2450431 (2.3M) [application/octet-stream]
Saving to: ‘robo.phar’

robo.phar                   100%[==========================================>]   2.34M  6.44MB/s    in 0.4s    

2018-05-31 19:48:10 (6.44 MB/s) - ‘robo.phar’ saved [2450431/2450431]

Password:
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ robo wordpress:setup

 This will replace your current WordPress install. Are you sure you want to do this? (yes/no) [no]:
 > yes

?  Do you have an existing database you'd like to use and configure yourself? (y/n):  n
 [Exec] Running brew install mysql
Warning: mysql 5.7.22 is already installed and up-to-date
To reinstall 5.7.22, run `brew reinstall mysql`
 [Exec] Done in 1.259s
 [Exec] Running mysql.server start
Starting MySQL
.. SUCCESS! 
 [Exec] Done in 2.029s
 [Exec] Running ./mysql_config.sh
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
 [Exec] Done in 0.02s
 [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e 'create user if not exists wp_headless'
mysql: [Warning] Using a password on the command line interface can be insecure.
 [Exec] Done in 0.072s
 [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e 'create database if not exists wp_headless'
mysql: [Warning] Using a password on the command line interface can be insecure.
 [Exec] Done in 0.046s
 [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e "grant all privileges on wp_headless.* to wp_headless@localhost identified by 'wp_headless'"
mysql: [Warning] Using a password on the command line interface can be insecure.
 [Exec] Done in 0.045s
 [Exec] Running mysql -uroot -proot -h 0.0.0.0 -e 'flush privileges'
mysql: [Warning] Using a password on the command line interface can be insecure.
 [Exec] Done in 0.045s
 [Exec] Running wp core download --version=4.9.5 --locale=en_US --force in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp core config --dbname=wp_headless --dbuser=wp_headless --dbpass=wp_headless --dbhost=0.0.0.0 in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp db drop --yes in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp db create in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.004s
 [Exec] Running wp core install --url=localhost:8080 --title="Postlight Headless WP Starter" --admin_user="nedstark" --admin_password="winteriscoming" --admin_email="nedstark@headlesswpstarter.dev" --skip-email in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp theme activate postlight-headless-wp in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp theme delete twentyfourteen in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp theme delete twentyfifteen in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp theme delete twentysixteen in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp theme delete twentyseventeen in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp plugin delete akismet in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp plugin delete hello in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.004s
 [Exec] Running wp plugin activate acf-to-wp-api advanced-custom-fields-pro custom-post-type-ui wp-graphql wp-migrate-db-pro wp-migrate-db-pro-cli wp-migrate-db-pro-media-files wp-rest-api-v2-menus in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp acf sync in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp rewrite structure "/%year%/%monthnum%/%day%/%postname%/" in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp option update blogdescription "Just another (headless) WordPress site by your friends at Postlight" in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp post update 1 wp-content/themes/postlight-headless-wp/post-content/sample-post.txt --post_title="Sample Post" --post_name=sample-post in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp post create wp-content/themes/postlight-headless-wp/post-content/welcome.txt --post_type=page --post_status=publish --post_name=welcome --post_title="Congratulations!" in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp term update category 1 --name="Sample Category" in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.004s
 [Exec] Running wp menu create "Header Menu" in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp menu item add-post header-menu 1 in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.003s
 [Exec] Running wp menu item add-post header-menu 2 in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp menu item add-term header-menu category 1 in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp menu item add-custom header-menu "Read about the Starter Kit on Medium" https://trackchanges.postlight.com/introducing-postlights-wordpress-react-starter-kit-a61e2633c48c in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
 [Exec] Running wp menu location assign header-menu header-menu in /Users/danboyle/Documents/level-up-tuts/headless-wp-starter/wordpress
sh: wp: command not found
 [Exec]  Exit code 127  Time 0.005s
                                                                                                               
 [OK] Great. You can now log into WordPress at: http://localhost:8080/wp-admin (nedstark/winteriscoming)       
                                                                                                               

✨  Done in 36.77s.

**Comment by thebiltheory** [comment]
See `wp: command not found`.

It is because `brew install wp-cli` is failing to install due to some sha key mismatch.
Just opened https://github.com/postlight/headless-wp-starter/issues/95

**Comment by danboyle8637** [comment]
Thanks @thebiltheory ... I followed the wp-cli installation manually, but still have this SHA256 mismatch. I did more research and can't get any solution to work yet. 

I appreciate the help.

**Comment by alvim54** [comment]
Hi @danboyle8637 , 
I had the same problem here. Solved it by deleting the file `/Users/{username}/Library/Caches/Homebrew/wp-cli-1.5.1.phar` and them manually installing wp-cli.

**Comment by thebiltheory** [comment]
Remove the old package: 
`rm -r /Users/danboyle/Library/Caches/Homebrew/wp-cli-1.5.1.phar`

It will re-download wp-cli using homebrew because it's in the install.sh script which  everytime you run.

Just in case
`brew cleanup`

then try to follow those steps again.
https://github.com/wp-cli/wp-cli#installing

After running `yarn install` you can ignore the SHA256 Error.

**Comment by glrodasz** [comment]
I'm having multiple errors. I have tried re-installing mysql but it didn't work.

```
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```

```
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'identified by 'wp_headless'' at line 1
```

```
ERROR 1045 (28000): Access denied for user 'wp_headless'@'localhost' (using password: YES)
```

**Comment by glrodasz** [comment]
I fixed the issue. Looks like Brew have change its mysql formula this week, so it is installing the new MySQL 8.0.11 that is incompatible with some queries that the scripts has to create users/permissions and it has an issue with PHP 7.1 `caching_sha2_password` https://stackoverflow.com/a/49950165

**The solution is remove MySQL 8 and and install MySQL 5.7 instead**.

For uninstall you can use:
https://gist.github.com/vitorbritto/0555879fe4414d18569d

For install MySQL 5.7:

1. `brew install mysql@5.7`
2. Run `mysql_secure_installation` (Select `n`, `root`, `root`, `y` `y`, `y`)
3. Make sure that you have exported the path in my case since I have zsh:
`echo 'export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"' >> ~/.zshrc`
4. Make sure that you can log in `mysql -uroot -p`

Notes:
- If you are having problems logging try to restart the service: `brew services restart mysql@5.7
- If the mysql CLI doesn't work make sure that you have exported the path or run `brew link --force --overwrite mysql@5.7`

After a succesfull login, you can install the project again runing `yarn install` and when he ask for your own version of mysql say `y`.

@ginatrapani I think this should go to the **Troubleshooting Common Errors** since the change of versions it is going to happen to any new user.

**Comment by trevorlitsey** [comment]
Amazing. This worked. Thank you!

**Comment by tristanoneil** [comment]
#105 should more permanently solve this issue.
