### ISSUE TITLE
GraphQL endpoint error

### ISSUE THREAD

**Issue by nathanqueija** [postlight/headless-wp-starter#97]
Hi, guys.
When I try to access graphl api through `http://localhost:8080/graphql` I get this error:

```
{
   "errors":[
      {
         "message":"Syntax Error GraphQL (1:1) Unexpected <EOF>\n\n1: \n   ^\n",
         "category":"graphql",
         "locations":[
            {
               "line":1,
               "column":1
            }
         ]
      }
   ]
}
```

I don't know why. Can you help me, please? Thanks.

**Comment by tristanoneil** [comment]
Are you passing a query to the endpoint? I believe [this is expected behavior](https://github.com/wp-graphql/wp-graphql/issues/451) if you're not. Does the frontend app work as expected?
