### ISSUE TITLE
What's the process to render custom post types?

### ISSUE THREAD

**Issue by kilinkis** [postlight/headless-wp-starter#98]
I searched the most I could but didn't find any documentation on how to show custom post types.

Creating the custom post types with UI Post Types (enabling it to be consumed via API) is pretty much a standard process, but what should we do after that with the react app?

I guess we need to at least update the router. How can we do this (I tried with no luck)?
What other steps are needed to render a custom post type on the front of our react app?

thank you so much

**Comment by jacobmishkin** [comment]
Have you been able to get this going, or do you still need help?

**Comment by kilinkis** [comment]
hello @jacobmishkin!
I couldn't get it to work. Can you tell me how to do it?
I'd really appreciate it. Thanks!

**Comment by jacobmishkin** [comment]
Not a problem. Are you working from a fresh install, or have you changed things in the code yet?

**Comment by kilinkis** [comment]
well, I did what I described in this other issue: https://github.com/postlight/headless-wp-starter/issues/93

but then it got out of hand to me, and started a fresh install :/

**Comment by jacobmishkin** [comment]
Cool.  

1. you want to create a CPT, remember to add show in REST in the CPT config. 

2. Make sure all the plugins are installed and activated.

3. Go to your inc folder under your WP backend and in the file api-routes.php you will need to do the following: 

a. create a new regester_rest_route function. Some are already created, I would use them as a base, or even just copy them, but remember to add your CPT name in the route argument as '/CPT__name__here' after the postlight/v1 route arg. 

b. change the callback function in your regester_rest_route to rest_get_cpt_name_here.

c. under the comment  Respond to a REST API request to get post data. Here you will need to add your callback function. see the step b. above if you need reference. copy and that function and add the same naming convention as others. 

d. scroll down and under the comment Respond to a REST API request to get post or page data. under the function rest_get_content add your named cpt to the array, 

e. do the same as above for get_content_by_slug function.

4. Check your REST API in either the browser or if you are using Postman, you should find the CPT. 

I hope this helps!

**Comment by kilinkis** [comment]
wow, thank you @jacobmishkin! I'll give a shot ASAP and let u know how it went.

**Comment by muigaiunaka** [comment]
@kilinkis did it end up working out? If you're still having trouble, these were the files that I ended up having to edit to get my CPT to render on the frontend:

- frontend/components/Menu.js
- frontend/pages/index.js
- frontend/pages/post.js
- frontend/server.js
- wordpress/wp-content/themes/postlight-headless-wp/inc/api-routes.php
- wordpress/wp-content/themes/postlight-headless-wp/index.php

happy to share a gist with the lines that I edited per file

**Comment by kilinkis** [comment]
@muigaiunaka I still get some 404 errors, would you mind sharing the gist please?

thank you very much!
